In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/laptop_dataset.csv")

C:\Users\SANDEEP\AppData\Local\Temp\ipykernel_32424\2960869190.py:3: DtypeWarning: Columns (0: Chipset, 1: RAM Speed, 2: Memory Slots, 3: SSD Type, 4: HDMI Ports, 5: Audio Solution, 6: Brightness, 7: Expandable Memory, 8: Thunderbolt Port, 9: VGA Port, 10: HDD Capacity, 11: HDD Speed(RPM), 12: HDD Type, 13: Lockport, 14: Battery Capacity, 15: Aspect Ratio, 16: SSD Interface, 17: Fast Charging Support) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/laptop_dataset.csv")

In [2]:
print("Shape:", df.shape)
print("Target:Price (Rs)")
print("Duplicate rows:", df.duplicated().sum())

Shape: (8198, 76)
Target:Price (Rs)
Duplicate rows: 1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8198 entries, 0 to 8197
Data columns (total 76 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Brand                       8198 non-null   str
 1   Model                       8198 non-null   str
 2   Series                      7105 non-null   str
 3   Thickness                   7518 non-null   str
 4   Dimensions (WxDxH)          7516 non-null   str
 5   Weight                      7891 non-null   str
 6   Colors                      8022 non-null   str
 7   Operating System            8198 non-null   str
 8   Operating System Type       4678 non-null   str
 9   Display Size                8195 non-null   str
 10  Display Resolution          8166 non-null   str
 11  Pixel Density               8164 non-null   str
 12  Display Type                4308 non-null   str
 13  Display Features            8066 non-null   str
 14  Display Touchscreen         8116 non-null   str
 15  Processor                   8198 non-null   str
 16  Clock-speed                 7727 non-null   str
 17  Chipset                     1051 non-null   str
 18  Cache                       6627 non-null   str
 19  Graphic Processor           8106 non-null   str
 20  Capacity                    8198 non-null   str
 21  RAM Type                    8028 non-null   str
 22  RAM Speed                   5105 non-null   str
 23  Memory Slots                8134 non-null   object
 24  Memory Layout               8042 non-null   str
 25  SSD Capacity                6864 non-null   str
 26  SSD Type                    2454 non-null   str
 27  Battery Cell                6892 non-null   str
 28  Battery Type                7461 non-null   str
 29  Power Supply                6781 non-null   str
 30  Wireless LAN                8124 non-null   str
 31  Wi-Fi Version               8124 non-null   float64
 32  Bluetooth                   8149 non-null   str
 33  Bluetooth Version           7380 non-null   float64
 34  Other Networking Options    2538 non-null   str
 35  HDMI Ports                  7441 non-null   object
 36  USB 2.0 slots               3225 non-null   float64
 37  SD Card Reader              4486 non-null   str
 38  Ethernet ports              3444 non-null   float64
 39  Headphone Jack              8184 non-null   str
 40  Microphone Jack             8181 non-null   str
 41  Web-cam                     7923 non-null   str
 42  Video Recording             7042 non-null   str
 43  Audio Solution              2636 non-null   str
 44  Speakers                    8089 non-null   str
 45  Sound Technologies          3633 non-null   str
 46  In-built Microphone         8010 non-null   str
 47  Microphone Type             7960 non-null   str
 48  Pointing device             5878 non-null   str
 49  Keyboard                    7120 non-null   str
 50  Fingerprint scanner         5510 non-null   str
 51  Face Recognition            2532 non-null   str
 52  Warranty                    7740 non-null   str
 53  Sales Package               8184 non-null   str
 54  Refresh Rate                3119 non-null   str
 55  Brightness                  2372 non-null   str
 56  Graphics Memory             3077 non-null   str
 57  Expandable Memory           3235 non-null   str
 58  Thunderbolt Port            993 non-null    str
 59  VGA Port                    3849 non-null   str
 60  Backlit Keyboard            4601 non-null   str
 61  HDD Capacity                1854 non-null   str
 62  HDD Speed(RPM)              1736 non-null   str
 63  HDD Type                    1729 non-null   str
 64  USB 3.0 slots               2223 non-null   float64
 65  Secondary cam(Rear-facing)  3232 non-null   str
 66  Lockport                    1534 non-null   str
 67  Battery Life                2722 non-null   str
 68  USB Type C                  5191 non-null   float64
 69  Battery Capacity            2454 non-null   str
 70  Aspect Ratio                1329 non-null   str
 71  Number of Cores             2925 non-null   float64
 72  SSD Interface               2053 non-null   str
 73  Fast Charging Support       940 non-null    str
 74  market_status               8198 non-null   str
 75  Price (Rs)                  8177 non-null   float64
dtypes: float64(8), object(2), str(66)
memory usage: 4.8+ MB

# missing values

In [6]:
df.isna().sum()

Brand                       0
Model                       0
Series                   1093
Thickness                 680
Dimensions (WxDxH)        682
                         ...
Number of Cores          5273
SSD Interface            6145
Fast Charging Support    7258
market_status               0
Price (Rs)                 21
Length: 76, dtype: int64

In [ ]:
print("total missing values",df.isna().sum().sum())

total missing values 191965

In [7]:
missing_count = df.isna().sum()

missing_summary = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percentage": (df.isna().mean() * 100).round(2)
})

missing_summary

                       Missing Count  Missing Percentage
Brand                              0                0.00
Model                              0                0.00
Series                          1093               13.33
Thickness                        680                8.29
Dimensions (WxDxH)               682                8.32
...                              ...                 ...
Number of Cores                 5273               64.32
SSD Interface                   6145               74.96
Fast Charging Support           7258               88.53
market_status                      0                0.00
Price (Rs)                        21                0.26

[76 rows x 2 columns]

In [8]:
missing_summary = (
    missing_summary[missing_summary["Missing Count"] > 0]
    .sort_values("Missing Percentage", ascending=False)
)
missing_summary

                       Missing Count  Missing Percentage
Fast Charging Support           7258               88.53
Thunderbolt Port                7205               87.89
Chipset                         7147               87.18
Aspect Ratio                    6869               83.79
Lockport                        6664               81.29
...                              ...                 ...
Price (Rs)                        21                0.26
Microphone Jack                   17                0.21
Headphone Jack                    14                0.17
Sales Package                     14                0.17
Display Size                       3                0.04

[70 rows x 2 columns]

### Target missing

In [9]:
print(df["Price (Rs)"].isna().sum())
print(round(df["Price (Rs)"].isna().mean() * 100, 2),"%")

21
0.26 %

In [10]:
df["Price (Rs)"].isna()

0       False
1       False
2       False
3       False
4       False
        ...
8193    False
8194    False
8195    False
8196    False
8197    False
Name: Price (Rs), Length: 8198, dtype: bool

In [11]:
missing_target_rows = df[df["Price (Rs)"].isna()]
missing_target_rows.shape

(21, 76)

In [12]:
missing_target_rows.head(22)

,Brand,Model,Series,Thickness,Dimensions (WxDxH),Weight,Colors,Operating System,Operating System Type,Display Size,...,Lockport,Battery Life,USB Type C,Battery Capacity,Aspect Ratio,Number of Cores,SSD Interface,Fast Charging Support,market_status,Price (Rs)
640,MSI,A2XWJG-253IN,NaN,32 Millimeter thickness,404 x 307.5 x 32 mm,3.6 Kg weight,Core Black,Windows 11 Home Basic,NaN,18 Inches (45.72 cm),...,Yes,NaN,NaN,99.9 WHrs,NaN,24.0,NVMe PCIe,NaN,Out of Stock,NaN
741,MSI,B12UCX-2243IN,Thin 15,21.7 Millimeter thickness,359 x 254 x 21.7 mm,1.86 Kg weight,Cosmos Gray,Windows 11 Home Basic,NaN,15.6 Inches (39.62 cm),...,Yes,NaN,1.0,52.4 WHrs,NaN,8.0,NVMe PCIe,NaN,Out of Stock,NaN
787,MSI,B12VE-2238IN,Thin 15,21.7 Millimeter thickness,359 x 254 x 21.7 mm,1.86 Kg weight,Cosmos Gray,Windows 11 Home Basic,NaN,15.6 Inches (39.62 cm),...,Yes,NaN,1.0,52.4 WHrs,NaN,10.0,NVMe PCIe,NaN,Out of Stock,NaN
789,MSI,B12VE-2085IN,Thin 15,21.7 Millimeter thickness,359 x 254 x 21.7 mm,1.86 Kg weight,Cosmos Gray,Windows 11 Home Basic,NaN,15.6 Inches (39.62 cm),...,Yes,NaN,1.0,52.4 WHrs,NaN,10.0,NVMe PCIe,NaN,Out of Stock,NaN
1076,MSI,B1MG-051IN,Prestige 16 AI Evo,18.9 Millimeter thickness,358.4 x 254.4 x 18.9 mm,1.5 Kg weight,Stellar Gray,Windows 11 Home Basic,NaN,16 Inches (40.64 cm),...,NaN,NaN,2.0,99.9 WHrs,NaN,16.0,NaN,NaN,Out of Stock,NaN
1097,MSI,C12M-460IN,Modern 14,19.3 Millimeter thickness,319.9 x 223 x 19.3 mm,1.4 Kg weight (Light-weight),Black,Windows 11 Home Basic,NaN,14 Inches (35.56 cm),...,NaN,NaN,1.0,39.3 WHrs,NaN,10.0,NaN,NaN,Out of Stock,NaN
4643,Coconics,C1314W,Enabler,24 Millimeter thickness,237 x 347 x 24 mm,1.83 Kg weight,Black,Windows 10 Home Basic,NaN,14 Inches (35.56 cm),...,NaN,5 Hrs,1.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
5383,Asus,G733QS-HG195TS,ROG Strix Scar 17,28.3 Millimeter thickness,395 x 282 x 28.3 mm,2.70 Kg weight,Eclipse Gray,Windows 10,NaN,17.3 Inches (43.94 cm),...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
5384,Razer,â€ŽRZ09-0369AE22-R3U1,Blade 15,20 Millimeter thickness,355 x 235 x 20 mm,2.90 Kg weight,Black,Windows 10 Home Basic,NaN,15.6 Inches (39.62 cm),...,NaN,6 Hrs,3.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
5396,Asus,G713RM-KH102WS,ROG Strix G17,28.3 Millimeter thickness,395 x 282 x 28.3 mm,2.90 Kg weight,Eclipse Gray,Windows 11 Home Basic,NaN,17.3 Inches (43.94 cm),...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
5397,Asus,G513RM-HF193WS,ROG Strix G15,27.2 Millimeter thickness,354 x 259 x 27.2 mm,2.30 Kg weight,Eclipse Gray,Windows 11 Home Basic,NaN,15.6 Inches (39.62 cm),...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
5398,Asus,G713RM-LL031WS,ROG Strix G17,28.3 Millimeter thickness,395 x 282 x 28.3 mm,2.90 Kg weight,Eclipse Gray,Windows 11 Home Basic,NaN,17.3 Inches (43.94 cm),...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
6043,HP,15-dy2795wm (6M0Z7UA),NaN,17.9 Millimeter thickness,358.5 x 242 x 17.9 mm,1.69 Kg weight,Silver,Windows 11 Home Basic,NaN,15.6 Inches (39.62 cm),...,NaN,9.15 Hrs,1.0,41 Hrs,NaN,4.0,NaN,NaN,Out of Stock,NaN
6048,Gigabyte,G6X 9MG 2024,NaN,NaN,NaN,2.5 Kg weight,Gunmetal Gray,Windows 11,NaN,16 Inches (40.64 cm),...,NaN,NaN,1.0,73 WHrs,16:10,NaN,NaN,NaN,Out of Stock,NaN
6064,LG,17Z90R-G.CH75A2,gram 17,17.8 Millimeter thickness,378.8 x 258.8 x 17.8 mm,1.35 Kg weight (Light-weight),Obsidian Black,Windows 11 Home Basic,NaN,17 Inches (43.18 cm),...,NaN,NaN,2.0,80 WHrs,16:10,NaN,NVMe,NaN,Out of Stock,NaN
8048,Acer,SP513-53N-53Y5 (NX.H62AA.008),Spin 5,15.2 Millimeter thickness (Slim),325.12 x 226.06 x 15.2 mm,1.60 Kg weight,Black,Windows 10 Home Basic,64-bit,13.3 Inches (33.78 cm),...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
8091,Lenovo,(80Y8005UIN),Yoga 920,14 Millimeter thickness (Slim),323 x 223 x 14 mm,1.37 Kg weight (Light-weight),Platinum Silver,Windows 10 Home Basic,64-bit,13.9 Inches (35.31 cm),...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
8111,Asus,G15 GA502I,ROG Zenphyrus,19.9 Millimeter thickness,360 x 252 x 19.9 mm,2.1 Kg weight,Black,Windows 10 Professional,64-bit,15.6 Inches (39.62 cm),...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
8118,Asus,G14,ROG Zenphyrus,17.9 Millimeter thickness,324 x 222 x 17.9 mm,1.6 Kg weight,Black,Windows 10 Home Basic,64-bit,14 Inches (35.56 cm),...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
8120,Dell,15 9510,Latitude 15,14 Millimeter thickness (Slim),340 x 215 x 14 mm,1.45 Kg weight (Light-weight),Silver,Windows 10 Home Basic,64-bit,15 Inches (38.1 cm),...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN
8144,Samsung,Notebook 9 Pro,Notebook 9 Pro,NaN,NaN,NaN,Silver,Windows 10 Home Basic,64-bit,13.3 Inches (33.78 cm),...,No,NaN,3.0,NaN,NaN,NaN,NaN,NaN,Out of Stock,NaN

In [13]:
missing_target_rows.isna().sum().sort_values(ascending=False).head(15)

HDD Speed(RPM)              21
Price (Rs)                  21
Fast Charging Support       21
USB 2.0 slots               20
HDD Type                    20
HDD Capacity                20
Aspect Ratio                19
Thunderbolt Port            19
USB 3.0 slots               19
Brightness                  19
Other Networking Options    18
Battery Life                18
Lockport                    16
SSD Interface               16
SSD Type                    15
dtype: int64

In [14]:
df = df.dropna(subset=["Price (Rs)"]).copy()

In [15]:
print("Shape after removing missing target rows:", df.shape)
print("Missing Price values:",df["Price (Rs)"].isna().sum())

Shape after removing missing target rows: (8177, 76)
Missing Price values: 0

## features values missing

In [16]:
feature_missing_summary = (
    df.drop(columns=["Price (Rs)"])
      .isna()
      .sum()
      .to_frame("Missing Count")
)

print(feature_missing_summary)
print("================")

feature_missing_summary["Missing Percentage"] = (
    feature_missing_summary["Missing Count"] / len(df) * 100
).round(2)

feature_missing_summary.sort_values("Missing Percentage",ascending=False)

                       Missing Count
Brand                              0
Model                              0
Series                          1090
Thickness                        678
Dimensions (WxDxH)               680
...                              ...
Aspect Ratio                    6850
Number of Cores                 5259
SSD Interface                   6129
Fast Charging Support           7237
market_status                      0

[75 rows x 1 columns]
================

                       Missing Count  Missing Percentage
Fast Charging Support           7237               88.50
Thunderbolt Port                7186               87.88
Chipset                         7133               87.23
Aspect Ratio                    6850               83.77
Lockport                        6648               81.30
...                              ...                 ...
Model                              0                0.00
Operating System                   0                0.00
Capacity                           0                0.00
Processor                          0                0.00
market_status                      0                0.00

[75 rows x 2 columns]

In [17]:
feature_missing_summary = (
    feature_missing_summary[feature_missing_summary["Missing Count"] > 0]
    .sort_values("Missing Percentage", ascending=False)
)

feature_missing_summary

                       Missing Count  Missing Percentage
Fast Charging Support           7237               88.50
Thunderbolt Port                7186               87.88
Chipset                         7133               87.23
Aspect Ratio                    6850               83.77
Lockport                        6648               81.30
...                              ...                 ...
Display Resolution                32                0.39
Microphone Jack                   16                0.20
Headphone Jack                    14                0.17
Sales Package                     14                0.17
Display Size                       3                0.04

[69 rows x 2 columns]

In [18]:
print(feature_missing_summary.to_string())

                            Missing Count  Missing Percentage
Fast Charging Support                7237               88.50
Thunderbolt Port                     7186               87.88
Chipset                              7133               87.23
Aspect Ratio                         6850               83.77
Lockport                             6648               81.30
HDD Type                             6449               78.87
HDD Speed(RPM)                       6441               78.77
HDD Capacity                         6324               77.34
SSD Interface                        6129               74.95
USB 3.0 slots                        5956               72.84
Brightness                           5807               71.02
Battery Capacity                     5732               70.10
SSD Type                             5729               70.06
Face Recognition                     5653               69.13
Other Networking Options             5642               69.00
Audio Solution                       5549               67.86
Battery Life                         5458               66.75
Number of Cores                      5259               64.31
Graphics Memory                      5112               62.52
Refresh Rate                         5069               61.99
USB 2.0 slots                        4953               60.57
Secondary cam(Rear-facing)           4951               60.55
Expandable Memory                    4949               60.52
Ethernet ports                       4742               57.99
Sound Technologies                   4553               55.68
VGA Port                             4336               53.03
Display Type                         3876               47.40
SD Card Reader                       3700               45.25
Backlit Keyboard                     3590               43.90
Operating System Type                3505               42.86
RAM Speed                            3082               37.69
USB Type C                           3006               36.76
Fingerprint scanner                  2674               32.70
Pointing device                      2311               28.26
Cache                                1560               19.08
Power Supply                         1414               17.29
SSD Capacity                         1333               16.30
Battery Cell                         1301               15.91
Video Recording                      1151               14.08
Series                               1090               13.33
Keyboard                             1074               13.13
Bluetooth Version                     815                9.97
HDMI Ports                            755                9.23
Battery Type                          730                8.93
Dimensions (WxDxH)                    680                8.32
Thickness                             678                8.29
Clock-speed                           467                5.71
Warranty                              446                5.45
Weight                                306                3.74
Web-cam                               271                3.31
Microphone Type                       235                2.87
In-built Microphone                   185                2.26
Colors                                176                2.15
RAM Type                              170                2.08
Memory Layout                         155                1.90
Display Features                      131                1.60
Speakers                              109                1.33
Graphic Processor                      92                1.13
Display Touchscreen                    82                1.00
Wireless LAN                           74                0.90
Wi-Fi Version                          74                0.90
Memory Slots                           63                0.77
Bluetooth                              48                0.59
Pixel Density                          34                0.42
Display Resolution                     32                0.39
Microphone Jack                        16                0.20
Headphone Jack                         14                0.17
Sales Package                          14                0.17
Display Size                            3                0.04

In [19]:
high_missing = feature_missing_summary[
    feature_missing_summary["Missing Percentage"] >= 50
]
high_missing

                            Missing Count  Missing Percentage
Fast Charging Support                7237               88.50
Thunderbolt Port                     7186               87.88
Chipset                              7133               87.23
Aspect Ratio                         6850               83.77
Lockport                             6648               81.30
HDD Type                             6449               78.87
HDD Speed(RPM)                       6441               78.77
HDD Capacity                         6324               77.34
SSD Interface                        6129               74.95
USB 3.0 slots                        5956               72.84
Brightness                           5807               71.02
Battery Capacity                     5732               70.10
SSD Type                             5729               70.06
Face Recognition                     5653               69.13
Other Networking Options             5642               69.00
Audio Solution                       5549               67.86
Battery Life                         5458               66.75
Number of Cores                      5259               64.31
Graphics Memory                      5112               62.52
Refresh Rate                         5069               61.99
USB 2.0 slots                        4953               60.57
Secondary cam(Rear-facing)           4951               60.55
Expandable Memory                    4949               60.52
Ethernet ports                       4742               57.99
Sound Technologies                   4553               55.68
VGA Port                             4336               53.03

In [20]:
for column in high_missing.index:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False).head(10))

--- Fast Charging Support ---
Fast Charging Support
NaN    7237
Yes     926
No       14
Name: count, dtype: int64

--- Thunderbolt Port ---
Thunderbolt Port
NaN                      7186
4.0                       969
4                          13
3.0                         6
Thunderbolt 4 (USB-C)       2
Thunderbolt 3 (USB-C)       1
Name: count, dtype: int64

--- Chipset ---
Chipset
NaN                     7133
Intel Integrated SoC     310
AMD Integrated SoC       112
Intel SoC Platform        80
Intel HM370 Express       74
Intel HM470               71
Intel HM770               60
Integrated SoC            39
Intel HM175 Express       38
AMD SoC Platform          37
Name: count, dtype: int64

--- Aspect Ratio ---
Aspect Ratio
NaN      6850
16:9      694
16:10     624
3:2         9
Name: count, dtype: int64

--- Lockport ---
Lockport
NaN    6648
Yes     798
No      731
Name: count, dtype: int64

--- HDD Type ---
HDD Type
NaN     6449
SATA    1728
Name: count, dtype: int64

--- HDD Speed(RPM) ---
HDD Speed(RPM)
NaN         6441
5400 RPM    1623
7200 RPM     113
Name: count, dtype: int64

--- HDD Capacity ---
HDD Capacity
NaN       6324
1 TB      1699
500 GB     107
2 TB        45
1 GB         1
256 GB       1
Name: count, dtype: int64

--- SSD Interface ---
SSD Interface
NaN          6129
NVMe PCIe    1628
PCIe          317
NVMe           90
SATA           13
Name: count, dtype: int64

--- USB 3.0 slots ---
USB 3.0 slots
NaN    5956
2.0    1037
1.0     958
3.0     182
4.0      40
5.0       3
6.0       1
Name: count, dtype: int64

--- Brightness ---
Brightness
NaN         5807
250 nits     923
300 nits     598
400 nits     274
500 nits     215
600 nits     104
220 nits      95
200 nits      36
350 nits      30
550 nits      25
Name: count, dtype: int64

--- Battery Capacity ---
Battery Capacity
NaN        5732
41 WHrs     183
42 WHrs     138
90 WHrs     116
50 WHrs      98
70 WHrs      94
45 WHrs      92
47 WHrs      83
54 WHrs      81
57 WHrs      80
Name: count, dtype: int64

--- SSD Type ---
SSD Type
NaN           5729
M.2           1821
M.2/Optane     627
Name: count, dtype: int64

--- Face Recognition ---
Face Recognition
NaN    5653
Yes    2055
No      469
Name: count, dtype: int64

--- Other Networking Options ---
Other Networking Options
NaN                                           5642
Multi-Format SD Media card Reader             1129
Multi-Format SD media card reader              568
Multi-Format SD Media Card Reader              201
Multi-Format SD media card reader (3-in-1)     190
Multi-Format SD media card reader (4-in-1)     152
1 multi-format SD media card reader             56
Multi Format SD Media Card Reader               39
Multi-Format SD media card reader (2-in-1)      22
SD Card Reader                                  20
Name: count, dtype: int64

--- Audio Solution ---
Audio Solution
NaN                  5549
Dolby Audio           327
Dolby Atmos           305
HD Audio Solution     257
Audio By B&O          226
Harman Kardon         191
HP Audio Boost        157
Nahimic Audio         130
Audio by B&O           90
SonicMaster            88
Name: count, dtype: int64

--- Battery Life ---
Battery Life
NaN       5458
6 Hrs      447
10 Hrs     307
8 Hrs      283
7 Hrs      230
5 Hrs      135
4 Hrs      121
12 Hrs     116
9 Hrs      111
11 Hrs     104
Name: count, dtype: int64

--- Number of Cores ---
Number of Cores
NaN     5259
8.0      619
10.0     521
6.0      451
4.0      298
2.0      250
12.0     247
14.0     215
16.0     213
24.0      67
Name: count, dtype: int64

--- Graphics Memory ---
Graphics Memory
NaN       5112
4 GB      1291
6 GB       640
2 GB       532
8 GB       458
16 GB       63
12 GB       42
3 GB        16
128 MB       6
4            4
Name: count, dtype: int64

--- Refresh Rate ---
Refresh Rate
NaN       5069
60 Hz     1149
144 Hz     823
120 Hz     556
165 Hz     248
240 Hz     171
90 Hz       86
300 Hz      54
360 Hz      16
30 Hz        2
Name: count, dtype: int64

--- USB 2.0 slots ---
USB 2.0 slots
NaN    4953
1.0    2204
2.0     982
3.0      38
Name: count, dtype: int64

--- Secondary cam(Rear-facing) ---
Secondary cam(Rear-facing)
NaN    4951
No     3189
Yes      37
Name: count, dtype: int64

--- Expandable Memory ---
Expandable Memory
NaN      4949
16 GB    1155
32 GB    1124
8 GB      309
64 GB     307
12 GB     239
4 GB       33
24 GB      32
48 GB      15
96 GB      10
Name: count, dtype: int64

--- Ethernet ports ---
Ethernet ports
NaN    4742
1.0    3433
2.0       2
Name: count, dtype: int64

--- Sound Technologies ---
Sound Technologies
NaN                             4553
Dolby Audio                      374
HD Audio                         299
HP Audio Boost                   278
Waves Maxx Audio Pro             189
Waves MaxxAudio Pro               93
Smart Amp Technology              93
Asus Sonic Master Technology      89
Bang & Olufsen                    76
Dolby Atmos                       67
Name: count, dtype: int64

--- VGA Port ---
VGA Port
NaN    4336
No     3423
Yes     418
Name: count, dtype: int64

In [21]:
high_missing_drop_columns = [
    "Fast Charging Support",
    "Thunderbolt Port",
    "Lockport",
    "Face Recognition",
    "Other Networking Options",
    "Audio Solution",
    "Secondary cam(Rear-facing)",
    "Sound Technologies",
    "VGA Port"
]

In [22]:
df[high_missing_drop_columns].isna().mean().mul(100).round(2)

Fast Charging Support         88.50
Thunderbolt Port              87.88
Lockport                      81.30
Face Recognition              69.13
Other Networking Options      69.00
Audio Solution                67.86
Secondary cam(Rear-facing)    60.55
Sound Technologies            55.68
VGA Port                      53.03
dtype: float64

In [23]:
df = df.drop(columns=high_missing_drop_columns)

In [24]:
print("New shape:", df.shape)
print("\nRemaining columns:")
print(df.columns.tolist())

New shape: (8177, 67)

Remaining columns:
['Brand', 'Model', 'Series', 'Thickness', 'Dimensions (WxDxH)', 'Weight', 'Colors', 'Operating System', 'Operating System Type', 'Display Size', 'Display Resolution', 'Pixel Density', 'Display Type', 'Display Features', 'Display Touchscreen', 'Processor', 'Clock-speed', 'Chipset', 'Cache', 'Graphic Processor', 'Capacity', 'RAM Type', 'RAM Speed', 'Memory Slots', 'Memory Layout', 'SSD Capacity', 'SSD Type', 'Battery Cell', 'Battery Type', 'Power Supply', 'Wireless LAN', 'Wi-Fi Version', 'Bluetooth', 'Bluetooth Version', 'HDMI Ports', 'USB 2.0 slots', 'SD Card Reader', 'Ethernet ports', 'Headphone Jack', 'Microphone Jack', 'Web-cam', 'Video Recording', 'Speakers', 'In-built Microphone', 'Microphone Type', 'Pointing device', 'Keyboard', 'Fingerprint scanner', 'Warranty', 'Sales Package', 'Refresh Rate', 'Brightness', 'Graphics Memory', 'Expandable Memory', 'Backlit Keyboard', 'HDD Capacity', 'HDD Speed(RPM)', 'HDD Type', 'USB 3.0 slots', 'Battery Life', 'USB Type C', 'Battery Capacity', 'Aspect Ratio', 'Number of Cores', 'SSD Interface', 'market_status', 'Price (Rs)']

In [25]:
missing_summary_remaining = (
    df.isnull().sum()
      .to_frame("Missing Count")
)

missing_summary_remaining["Missing Percentage"] = (
    missing_summary_remaining["Missing Count"] / len(df) * 100
).round(2)

missing_summary_remaining = (
    missing_summary_remaining[missing_summary_remaining["Missing Count"] > 0]
    .sort_values("Missing Percentage", ascending=False)
)

missing_summary_remaining

                       Missing Count  Missing Percentage
Chipset                         7133               87.23
Aspect Ratio                    6850               83.77
HDD Type                        6449               78.87
HDD Speed(RPM)                  6441               78.77
HDD Capacity                    6324               77.34
SSD Interface                   6129               74.95
USB 3.0 slots                   5956               72.84
Brightness                      5807               71.02
Battery Capacity                5732               70.10
SSD Type                        5729               70.06
Battery Life                    5458               66.75
Number of Cores                 5259               64.31
Graphics Memory                 5112               62.52
Refresh Rate                    5069               61.99
USB 2.0 slots                   4953               60.57
Expandable Memory               4949               60.52
Ethernet ports                  4742               57.99
Display Type                    3876               47.40
SD Card Reader                  3700               45.25
Backlit Keyboard                3590               43.90
Operating System Type           3505               42.86
RAM Speed                       3082               37.69
USB Type C                      3006               36.76
Fingerprint scanner             2674               32.70
Pointing device                 2311               28.26
Cache                           1560               19.08
Power Supply                    1414               17.29
SSD Capacity                    1333               16.30
Battery Cell                    1301               15.91
Video Recording                 1151               14.08
Series                          1090               13.33
Keyboard                        1074               13.13
Bluetooth Version                815                9.97
HDMI Ports                       755                9.23
Battery Type                     730                8.93
Dimensions (WxDxH)               680                8.32
Thickness                        678                8.29
Clock-speed                      467                5.71
Warranty                         446                5.45
Weight                           306                3.74
Web-cam                          271                3.31
Microphone Type                  235                2.87
In-built Microphone              185                2.26
Colors                           176                2.15
RAM Type                         170                2.08
Memory Layout                    155                1.90
Display Features                 131                1.60
Speakers                         109                1.33
Graphic Processor                 92                1.13
Display Touchscreen               82                1.00
Wi-Fi Version                     74                0.90
Wireless LAN                      74                0.90
Memory Slots                      63                0.77
Bluetooth                         48                0.59
Pixel Density                     34                0.42
Display Resolution                32                0.39
Microphone Jack                   16                0.20
Headphone Jack                    14                0.17
Sales Package                     14                0.17
Display Size                       3                0.04

In [27]:
missing_under_50 = (
    missing_summary_remaining[
        (missing_summary_remaining["Missing Count"] > 0) &
        (missing_summary_remaining["Missing Percentage"] <= 50)
    ]
    .sort_values("Missing Percentage", ascending=False)
)

missing_under_50

                       Missing Count  Missing Percentage
Display Type                    3876               47.40
SD Card Reader                  3700               45.25
Backlit Keyboard                3590               43.90
Operating System Type           3505               42.86
RAM Speed                       3082               37.69
USB Type C                      3006               36.76
Fingerprint scanner             2674               32.70
Pointing device                 2311               28.26
Cache                           1560               19.08
Power Supply                    1414               17.29
SSD Capacity                    1333               16.30
Battery Cell                    1301               15.91
Video Recording                 1151               14.08
Series                          1090               13.33
Keyboard                        1074               13.13
Bluetooth Version                815                9.97
HDMI Ports                       755                9.23
Battery Type                     730                8.93
Dimensions (WxDxH)               680                8.32
Thickness                        678                8.29
Clock-speed                      467                5.71
Warranty                         446                5.45
Weight                           306                3.74
Web-cam                          271                3.31
Microphone Type                  235                2.87
In-built Microphone              185                2.26
Colors                           176                2.15
RAM Type                         170                2.08
Memory Layout                    155                1.90
Display Features                 131                1.60
Speakers                         109                1.33
Graphic Processor                 92                1.13
Display Touchscreen               82                1.00
Wi-Fi Version                     74                0.90
Wireless LAN                      74                0.90
Memory Slots                      63                0.77
Bluetooth                         48                0.59
Pixel Density                     34                0.42
Display Resolution                32                0.39
Microphone Jack                   16                0.20
Headphone Jack                    14                0.17
Sales Package                     14                0.17
Display Size                       3                0.04

# Duplicate Cleaning

In [28]:
duplicate_rows = df[df.duplicated(keep=False)]
duplicate_rows

,Brand,Model,Series,Thickness,Dimensions (WxDxH),Weight,Colors,Operating System,Operating System Type,Display Size,...,HDD Type,USB 3.0 slots,Battery Life,USB Type C,Battery Capacity,Aspect Ratio,Number of Cores,SSD Interface,market_status,Price (Rs)
5846,Lenovo,14IRL8 (82YL00AYIN),Yoga 7,16.4 Millimeter thickness,317.87 x 222.50 x 16.4 mm,1.49 Kg weight (Light-weight),Storm Grey,Windows 11 Home Basic,NaN,14 Inches (35.56 cm),...,NaN,NaN,NaN,NaN,71 WHrs,NaN,12.0,NaN,Available,86190.0
5851,Lenovo,14IRL8 (82YL00AYIN),Yoga 7,16.4 Millimeter thickness,317.87 x 222.50 x 16.4 mm,1.49 Kg weight (Light-weight),Storm Grey,Windows 11 Home Basic,NaN,14 Inches (35.56 cm),...,NaN,NaN,NaN,NaN,71 WHrs,NaN,12.0,NaN,Available,86190.0

In [29]:
df.shape

(8177, 67)

In [30]:
df = df.drop_duplicates().copy()

In [31]:
print("Shape after removing duplicates:", df.shape)
print("Remaining duplicate rows:", df.duplicated().sum())

Shape after removing duplicates: (8176, 67)
Remaining duplicate rows: 0

# Invalid & Inconsistent Data

In [32]:
categorical_columns = df.select_dtypes(include=["object", "string"]).columns

print("Categorical columns:", len(categorical_columns))

for column in categorical_columns:
    print(column)

Categorical columns: 59
Brand
Model
Series
Thickness
Dimensions (WxDxH)
Weight
Colors
Operating System
Operating System Type
Display Size
Display Resolution
Pixel Density
Display Type
Display Features
Display Touchscreen
Processor
Clock-speed
Chipset
Cache
Graphic Processor
Capacity
RAM Type
RAM Speed
Memory Slots
Memory Layout
SSD Capacity
SSD Type
Battery Cell
Battery Type
Power Supply
Wireless LAN
Bluetooth
HDMI Ports
SD Card Reader
Headphone Jack
Microphone Jack
Web-cam
Video Recording
Speakers
In-built Microphone
Microphone Type
Pointing device
Keyboard
Fingerprint scanner
Warranty
Sales Package
Refresh Rate
Brightness
Graphics Memory
Expandable Memory
Backlit Keyboard
HDD Capacity
HDD Speed(RPM)
HDD Type
Battery Life
Battery Capacity
Aspect Ratio
SSD Interface
market_status

In [33]:
for column in categorical_columns:
    values = df[column].dropna().astype(str)
    original_unique = values.nunique()
    print(column,":",original_unique)

Brand : 35
Model : 8116
Series : 532
Thickness : 273
Dimensions (WxDxH) : 2274
Weight : 252
Colors : 492
Operating System : 32
Operating System Type : 2
Display Size : 42
Display Resolution : 57
Pixel Density : 112
Display Type : 11
Display Features : 3457
Display Touchscreen : 2
Processor : 746
Clock-speed : 49
Chipset : 61
Cache : 50
Graphic Processor : 388
Capacity : 14
RAM Type : 10
RAM Speed : 72
Memory Slots : 15
Memory Layout : 73
SSD Capacity : 15
SSD Type : 2
Battery Cell : 11
Battery Type : 2
Power Supply : 199
Wireless LAN : 6
Bluetooth : 2
HDMI Ports : 7
SD Card Reader : 2
Headphone Jack : 2
Microphone Jack : 2
Web-cam : 2
Video Recording : 31
Speakers : 260
In-built Microphone : 2
Microphone Type : 242
Pointing device : 338
Keyboard : 997
Fingerprint scanner : 6
Warranty : 13
Sales Package : 76
Refresh Rate : 12
Brightness : 21
Graphics Memory : 15
Expandable Memory : 12
Backlit Keyboard : 636
HDD Capacity : 5
HDD Speed(RPM) : 2
HDD Type : 1
Battery Life : 121
Battery Capacity : 123
Aspect Ratio : 3
SSD Interface : 4
market_status : 2

In [34]:
col=[]
org=[]
nor=[]
for column in categorical_columns:
    col.append(column)
    values = df[column].dropna().astype(str)
    original_unique = values.nunique()
    normalized_unique = (values.str.strip().str.lower().nunique())
    org.append(original_unique)
    nor.append(normalized_unique)

pd.DataFrame({"column":col,"unique_values":org,"normalized_values":nor})

                   column  unique_values  normalized_values
0                   Brand             35                 35
1                   Model           8116               8116
2                  Series            532                532
3               Thickness            273                273
4      Dimensions (WxDxH)           2274               2274
5                  Weight            252                252
6                  Colors            492                470
7        Operating System             32                 32
8   Operating System Type              2                  2
9            Display Size             42                 42
10     Display Resolution             57                 57
11          Pixel Density            112                112
12           Display Type             11                 11
13       Display Features           3457               3245
14    Display Touchscreen              2                  2
15              Processor            746                731
16            Clock-speed             49                 49
17                Chipset             61                 58
18                  Cache             50                 50
19      Graphic Processor            388                334
20               Capacity             14                 14
21               RAM Type             10                 10
22              RAM Speed             72                 72
23           Memory Slots             15                 15
24          Memory Layout             73                 72
25           SSD Capacity             15                 15
26               SSD Type              2                  2
27           Battery Cell             11                 11
28           Battery Type              2                  2
29           Power Supply            199                191
30           Wireless LAN              6                  6
31              Bluetooth              2                  2
32             HDMI Ports              7                  7
33         SD Card Reader              2                  2
34         Headphone Jack              2                  2
35        Microphone Jack              2                  2
36                Web-cam              2                  2
37        Video Recording             31                 27
38               Speakers            260                221
39    In-built Microphone              2                  2
40        Microphone Type            242                176
41        Pointing device            338                269
42               Keyboard            997                807
43    Fingerprint scanner              6                  6
44               Warranty             13                 13
45          Sales Package             76                 74
46           Refresh Rate             12                 12
47             Brightness             21                 21
48        Graphics Memory             15                 15
49      Expandable Memory             12                 12
50       Backlit Keyboard            636                528
51           HDD Capacity              5                  5
52         HDD Speed(RPM)              2                  2
53               HDD Type              1                  1
54           Battery Life            121                121
55       Battery Capacity            123                123
56           Aspect Ratio              3                  3
57          SSD Interface              4                  4
58          market_status              2                  2

In [35]:
inconsistent_columns = []

for column in categorical_columns:

    values = df[column].dropna().astype(str)
    original_unique = values.nunique()
    normalized_unique = (
        values
        .str.strip()
        .str.lower()
        .nunique()
    )

    if normalized_unique < original_unique:
        inconsistent_columns.append(column)

print("Potentially inconsistent columns:")
print(inconsistent_columns)
print("total:",len(inconsistent_columns))

Potentially inconsistent columns:
['Colors', 'Display Features', 'Processor', 'Chipset', 'Graphic Processor', 'Memory Layout', 'Power Supply', 'Video Recording', 'Speakers', 'Microphone Type', 'Pointing device', 'Keyboard', 'Sales Package', 'Backlit Keyboard']
total: 14

In [36]:
for column in inconsistent_columns:

    values = df[column].dropna().astype(str)

    normalized = values.str.strip().str.lower()

    comparison = pd.DataFrame({
        "Original": values,
        "Normalized": normalized
    })

    conflicts = comparison[
        comparison["Original"] != comparison["Normalized"]
    ].drop_duplicates()

    print(f"\n{'=' * 70}")
    print(column)
    print(f"{'=' * 70}")

    print(conflicts.head(20))

======================================================================
Colors
======================================================================
                         Original                     Normalized
0                   Tranquil Pink                  tranquil pink
1                           Black                          black
2                 Platinum Silver                platinum silver
4   Carbon Black, Platinum Silver  carbon black, platinum silver
5                  Natural Silver                 natural silver
6                            Grey                           grey
8                      Quiet Blue                     quiet blue
10                    Arctic Grey                    arctic grey
11                      Star Grey                      star grey
15                         Silver                         silver
17             Transparent Silver             transparent silver
18                     Abyss Blue                     abyss blue
23                   Urban Silver                   urban silver
28                   Shadow Black                   shadow black
29                     Onyx Black                     onyx black
33                  Phantom Black                  phantom black
34                  Charcoal Blue                  charcoal blue
35                 Mineral silver                 mineral silver
36                 Charcoal Black                 charcoal black
38                      Soft Mint                      soft mint

======================================================================
Display Features
======================================================================
                                             Original  \
0   Full HD LED Backlit Anti-glare IPS Micro-edge ...
1   Display with IPS (In-Plane Switching) Technolo...
2              Full HD LED Backlit Anti-glare Display
3     Full HD LED Backlit Wideview Anti-glare Display
4                                 HD AG Narrow Border
5   Diagonal   Full HD Micro-edge   anti-glare   2...
6                          Full HD Anti-glare Display
7                 Full HD LED IPS Multi-touch Display
8                          NanoEdge 2.8K OLED display
9             NanoEdge Anti-Glare LED-Backlit Display
10  Full HD LED Backlit   Anti-Glare Display (250 ...
11  Full HD LED Backlit Anti-glare IPS Touch Displ...
12         Full HD LED Backlit Anti-Glare TFT Display
13                        Full HD LED Backlit Display
14                             HD LED backlit Display
15                    Full HD LED Backlit IPS Display
16         Full HD IPS LED Backlit Anti-glare Display
17  Full HD LED Backlit Anti-glare Display (16:9 A...
18  Full HD (IPS 300nits Anti-glare   45% NTSC) Di...
19  Full HD   2%NTSC IPS-Level   close to 100%sRGB...

                                           Normalized
0   full hd led backlit anti-glare ips micro-edge ...
1   display with ips (in-plane switching) technolo...
2              full hd led backlit anti-glare display
3     full hd led backlit wideview anti-glare display
4                                 hd ag narrow border
5   diagonal   full hd micro-edge   anti-glare   2...
6                          full hd anti-glare display
7                 full hd led ips multi-touch display
8                          nanoedge 2.8k oled display
9             nanoedge anti-glare led-backlit display
10  full hd led backlit   anti-glare display (250 ...
11  full hd led backlit anti-glare ips touch displ...
12         full hd led backlit anti-glare tft display
13                        full hd led backlit display
14                             hd led backlit display
15                    full hd led backlit ips display
16         full hd ips led backlit anti-glare display
17  full hd led backlit anti-glare display (16:9 a...
18  full hd (ips 300nits anti-glare   45% ntsc) di...
19  full hd   2%ntsc ips-level   close to 100%srgb...

======================================================================
Processor
======================================================================
                            Original                        Normalized
0    Intel Core i5-1135G7 (11th Gen)   intel core i5-1135g7 (11th gen)
1   Intel Core i7-13700HX (13th Gen)  intel core i7-13700hx (13th gen)
2      Intel Core i5-8250U (8th Gen)     intel core i5-8250u (8th gen)
3     Intel Core i7-7700HQ (7th Gen)    intel core i7-7700hq (7th gen)
4         AMD Dual Core Athlon 3050U        amd dual core athlon 3050u
5        AMD Hexa Core Ryzen 5 4500U       amd hexa core ryzen 5 4500u
6    Intel Core i5-10210U (10th Gen)   intel core i5-10210u (10th gen)
7      Intel Pentium Quad Core N4200     intel pentium quad core n4200
8        AMD Octa Core Ryzen 7-5800H       amd octa core ryzen 7-5800h
11   Intel Core i3-10110U (10th Gen)   intel core i3-10110u (10th gen)
12     Intel Core i5-7200U (7th Gen)     intel core i5-7200u (7th gen)
13    Intel Core i5-7300HQ (7th Gen)    intel core i5-7300hq (7th gen)
15   Intel Core i5-10510U (10th Gen)   intel core i5-10510u (10th gen)
16       AMD Hexa Core Ryzen 5 4600H       amd hexa core ryzen 5 4600h
17   Intel Core i5-1035G1 (10th Gen)   intel core i5-1035g1 (10th gen)
18       AMD Hexa Core Ryzen 5 5500U       amd hexa core ryzen 5 5500u
19       AMD Octa Core Ryzen 7 5800H       amd octa core ryzen 7 5800h
21     AMD Octa Core Ryzen 7 - 5800H     amd octa core ryzen 7 - 5800h
22   Intel Core i3-1005G1 (10th Gen)   intel core i3-1005g1 (10th gen)
23    Intel Core i5-1235U (12th Gen)    intel core i5-1235u (12th gen)

======================================================================
Chipset
======================================================================
                  Original             Normalized
0                Intel SoC              intel soc
20                   Intel                  intel
24     Intel HM370 Express    intel hm370 express
28    Intel Integrated SoC   intel integrated soc
29             Intel HM470            intel hm470
54      AMD Integrated SoC     amd integrated soc
74     Intel HM170 Express    intel hm170 express
76                 AMD Soc                amd soc
89     Intel HM175 Express    intel hm175 express
134     Intel HM87 Express     intel hm87 express
176            Intel HM370            intel hm370
200     Intel QM87 Express     intel qm87 express
210      Intel HM76 Expres      intel hm76 expres
213     Intel HM86 Express     intel hm86 express
226     Intel HM76 Express     intel hm76 express
234     Intel HM65 Express     intel hm65 express
297    Mobile HM65 Express    mobile hm65 express
321                  6200U                  6200u
355  MediaTek SoC Platform  mediatek soc platform
376            Intel HM770            intel hm770

======================================================================
Graphic Processor
======================================================================
                      Original                  Normalized
0                 Intel Iris X                intel iris x
1      NVIDIA GeForce RTX 4050     nvidia geforce rtx 4050
2               AMD Radeon 530              amd radeon 530
3      NVIDIA GeForce GTX 1050     nvidia geforce gtx 1050
4                   AMD Radeon                  amd radeon
6    Intel Integrated Graphics   intel integrated graphics
7            Intel HD Graphics           intel hd graphics
8      NVIDIA GeForce RTX 3050     nvidia geforce rtx 3050
9                Intel UHD 620               intel uhd 620
10               Intel Iris Xe               intel iris xe
11                   Intel UHD                   intel uhd
12        NVIDIA Geforce MX130        nvidia geforce mx130
13    NVIDIA GeForce GTX 1050T    nvidia geforce gtx 1050t
14          AMD Radeon R5 M430          amd radeon r5 m430
16     NVIDIA GeForce GTX 1650     nvidia geforce gtx 1650
19         AMD Radeon RX 6600M         amd radeon rx 6600m
24     NVIDIA GeForce GTX 1060     nvidia geforce gtx 1060
26               AMD Radeon R2               amd radeon r2
29  NVIDIA Geforce GTX 1650 Ti  nvidia geforce gtx 1650 ti
31           AMD Radeon Vega 8           amd radeon vega 8

======================================================================
Memory Layout
======================================================================
            Original       Normalized
0       2x8 Gigabyte     2x8 gigabyte
1      1*16 Gigabyte    1*16 gigabyte
2     1 x 8 Gigabyte   1 x 8 gigabyte
3       1x8 Gigabyte     1x8 gigabyte
7       1x4 Gigabyte     1x4 gigabyte
14    1 x 4 Gigabyte   1 x 4 gigabyte
19     1x16 Gigabyte    1x16 gigabyte
20      1*8 Gigabyte     1*8 gigabyte
29      2x4 Gigabyte     2x4 gigabyte
30      2*4 Gigabyte     2*4 gigabyte
35      1*4 Gigabyte     1*4 gigabyte
47    2 x 4 Gigabyte   2 x 4 gigabyte
74   1 x 16 Gigabyte  1 x 16 gigabyte
92      2*8 Gigabyte     2*8 gigabyte
139     2x2 Gigabyte     2x2 gigabyte
155    1*32 Gigabyte    1*32 gigabyte
209   1 x 2 Gigabyte   1 x 2 gigabyte
225   2 x 2 Gigabyte   2 x 2 gigabyte
249       1 x 4 Byte       1 x 4 byte
285    2x16 Gigabyte    2x16 gigabyte

======================================================================
Power Supply
======================================================================
              Original          Normalized
0    43 W AC Adapter W   43 w ac adapter w
1                230 W               230 w
2    42 W AC Adapter W   42 w ac adapter w
4                 65 W                65 w
5    65 W AC Adapter W   65 w ac adapter w
7    38 W AC Adapter W   38 w ac adapter w
9    50 W AC Adapter W   50 w ac adapter w
11   45 W AC Adapter W   45 w ac adapter w
14   40 W AC Adapter W   40 w ac adapter w
19  180 W AC Adapter W  180 w ac adapter w
20                37 W                37 w
21               180 W               180 w
22                45 W                45 w
24  135 W AC Adapter W  135 w ac adapter w
27  150 W AC Adapter W  150 w ac adapter w
33  170 W AC Adapter W  170 w ac adapter w
39                24 W                24 w
45                41 W                41 w
49  120 W AC Adapter W  120 w ac adapter w
55              52.5 W              52.5 w

======================================================================
Video Recording
======================================================================
                                   Original  \
0                                   720p HD
2                                   HD 720p
13                                 1080p HD
193                                 720P HD
224                               1080p FHD
358                               1080P FHD
748                       1080p FaceTime HD
755                               1440p QHD
1124                             720p HD IR
1142                   1080p FHD RGB Camera
1145                            720p HD RGB
1147                   1080p FHD-RGB Camera
1149                     720p HD RGB camera
1151                     720p HD RGB Camera
1155                               1440p HD
1883  1080p FHD camera with privacy shutter
2224               1080p FaceTime HD Camera
2270                          1080p FHD RGB
2302                          1440p Quad HD
3120           720p HD With privacy shutter

                                 Normalized
0                                   720p hd
2                                   hd 720p
13                                 1080p hd
193                                 720p hd
224                               1080p fhd
358                               1080p fhd
748                       1080p facetime hd
755                               1440p qhd
1124                             720p hd ir
1142                   1080p fhd rgb camera
1145                            720p hd rgb
1147                   1080p fhd-rgb camera
1149                     720p hd rgb camera
1151                     720p hd rgb camera
1155                               1440p hd
1883  1080p fhd camera with privacy shutter
2224               1080p facetime hd camera
2270                          1080p fhd rgb
2302                          1440p quad hd
3120           720p hd with privacy shutter

======================================================================
Speakers
======================================================================
                                         Original  \
0                                   Dual Speakers
1                                 Stereo Speakers
3                                   Quad Speakers
4                               Built-in Speakers
8                                Built-in Speaker
10                  Built-in Dual Stereo Speakers
18                       Built-in Stereo Speakers
19                         Built-in Dual Speakers
23                              Built-In Speakers
33   Built-In Harman Branded Dual Stereo Speakers
36                   Two built-in stereo speakers
46                             HARMAN Speaker x 2
52                                         Stereo
57                      Four-Speaker Sound System
74                                  Four Speakers
80                                  Dual speakers
81                                Stereo speakers
87                  Built-in dual stereo speakers
92                               2-Speaker System
106                        Built-In Dual Speakers

                                       Normalized
0                                   dual speakers
1                                 stereo speakers
3                                   quad speakers
4                               built-in speakers
8                                built-in speaker
10                  built-in dual stereo speakers
18                       built-in stereo speakers
19                         built-in dual speakers
23                              built-in speakers
33   built-in harman branded dual stereo speakers
36                   two built-in stereo speakers
46                             harman speaker x 2
52                                         stereo
57                      four-speaker sound system
74                                  four speakers
80                                  dual speakers
81                                stereo speakers
87                  built-in dual stereo speakers
92                               2-speaker system
106                        built-in dual speakers

======================================================================
Microphone Type
======================================================================
                                             Original  \
0                       Dual Array Digital Microphone
1                                Built-In Microphones
3                                  Digital Microphone
5            Integrated Dual Array Digital Microphone
6                                 Built-in Microphone
7                                 Internal Microphone
9   Dual Array Digital Microphone with Cortana voi...
10                     Built-In Dual Array Microphone
11                          Built-in Array Microphone
13                                Monaural Microphone
21                               Built-in Microphones
24                            Dual Digital Microphone
25            Built-in Dual Array Digital Microphones
27                     Dual Array Digital Microphones
29                   Integrated Dual Array Microphone
35           Integrated dual array digital microphone
36                           Built-in Dual Microphone
43                                Built In Microphone
48                     Integrated Monaural Microphone
50                           Built-In Dual Microphone

                                           Normalized
0                       dual array digital microphone
1                                built-in microphones
3                                  digital microphone
5            integrated dual array digital microphone
6                                 built-in microphone
7                                 internal microphone
9   dual array digital microphone with cortana voi...
10                     built-in dual array microphone
11                          built-in array microphone
13                                monaural microphone
21                               built-in microphones
24                            dual digital microphone
25            built-in dual array digital microphones
27                     dual array digital microphones
29                   integrated dual array microphone
35           integrated dual array digital microphone
36                           built-in dual microphone
43                                built in microphone
48                     integrated monaural microphone
50                           built-in dual microphone

======================================================================
Pointing device
======================================================================
                                             Original  \
0           Touchpad with Multi-touch Gesture Support
1   Multi-Gesture Touchpad, Supporting Two-Finger ...
3          Touchpad with Multi-Touch Gestures Enabled
4                                            Touchpad
9   Precision touchpad (PTP) technology supports u...
14         Touchpad with Multi-touch Gestures support
15          Touchpad with multi-touch gesture support
26          Touchpad with Multi-Touch gesture Support
35       Hp imagepad With multi-touch gesture support
39  TOUCH PAD HID-I2C 10PIN AMR11373-PCT1336U-6WB-...
40  HP Imagepad with multi-touch gesture support; ...
43  Multi-Gesture Touchpad, Supporting Two-Finger ...
45       HP Imagepad with multi-touch gesture support
46                                           Clickpad
50          Touchpad With Multi-Touch Gesture Support
52                                           ClickPad
55  HP Imagepad With Multi-touch Gesture Support P...
57                                           Trackpad
68  Multi-gesture touchpad, supporting two-finger ...
74          Touchpad with Multi-touch Gesture support

                                           Normalized
0           touchpad with multi-touch gesture support
1   multi-gesture touchpad, supporting two-finger ...
3          touchpad with multi-touch gestures enabled
4                                            touchpad
9   precision touchpad (ptp) technology supports u...
14         touchpad with multi-touch gestures support
15          touchpad with multi-touch gesture support
26          touchpad with multi-touch gesture support
35       hp imagepad with multi-touch gesture support
39  touch pad hid-i2c 10pin amr11373-pct1336u-6wb-...
40  hp imagepad with multi-touch gesture support; ...
43  multi-gesture touchpad, supporting two-finger ...
45       hp imagepad with multi-touch gesture support
46                                           clickpad
50          touchpad with multi-touch gesture support
52                                           clickpad
55  hp imagepad with multi-touch gesture support p...
57                                           trackpad
68  multi-gesture touchpad, supporting two-finger ...
74          touchpad with multi-touch gesture support

======================================================================
Keyboard
======================================================================
                                             Original  \
0                          Standard Notebook Keyboard
1   103-/104-/107-Key FineTip RGB- Keyboard With I...
3   Steelseries Gaming Backlight Keyboard (Red Color)
4                  English International Non Keyboard
9                   Full-size , with 1.4mm key travel
10                          Standard English Keyboard
11                                   Chiclet Keyboard
13  Full-sized Spill-resistant Keyboard with Numer...

In [37]:
for column in inconsistent_columns:
    df[column] = (
        df[column]
        .astype("string")
        .str.strip()
        .str.lower()
    )

In [38]:
for column in inconsistent_columns:

    values = df[column].dropna().astype(str)

    normalized = values.str.strip().str.lower()

    if values.nunique() != normalized.nunique():
        print(column)
        print("Still has formatting differences")

# Text-Encoded Numerical Specifications

In [39]:
text_columns = df.select_dtypes(
    include=["object", "string"]
).columns

print("Number of text columns:", len(text_columns))

for column in text_columns:
    print(f"\n--- {column} ---")
    print(df[column].dropna().head(10).to_list())

Number of text columns: 59

--- Brand ---
['HP', 'Acer', 'Dell', 'MSI', 'Dell', 'HP', 'Lenovo', 'iBall', 'Asus', 'Asus']

--- Model ---
['14-dv0055TU (2N1L1PA)', 'PHN16-71 (NH.QLTSI.002)', '15 5570 (A560126WIN9)', 'GV62 7RD-2297XIN', '15 3515 (D560702WIN9BE)', '15s-ey1004AU (38Z30PA)', '(81WE0144IN)', 'CompBook Premio v3.0', '14 OLED M3401QC-KM045WS', 'UX430UA-GV334T']

--- Series ---
['Pavilion', 'Predator Helios Neo 16', 'Inspiron 15', 'Inspiron 15', 'Ideapad Slim 3i', 'VivoBook Pro', 'Zenbook', 'Ideapad', 'VivoBook Flip 14', 'Aspire 5']

--- Thickness ---
['17 Millimeter thickness', '26.5 Millimeter thickness', '22.7 Millimeter thickness', '29 Millimeter thickness', '23 Millimeter thickness', '17.9 Millimeter thickness', '19.9 Millimeter thickness', '24 Millimeter thickness', '19 Millimeter thickness', '15.9 Millimeter thickness (Slim)']

--- Dimensions (WxDxH) ---
['325 x 216 x 17 \xa0mm', '361 x 279 x 26.5 \xa0mm', '380 x 258 x 22.7 \xa0mm', '383 x 260 x 29 \xa0mm', '358.50 x 17.50 x 23 \xa0mm', '358.5 x 242 x 17.9 \xa0mm', '362.2 x 253.4 x 19.9 \xa0mm', '334 x 222 x 24 \xa0mm', '317 x 229 x 19 \xa0mm', '324 x 225 x 15.9 \xa0mm']

--- Weight ---
['1.41 Kg weight (Light-weight)', '2.6 Kg weight', '2.2 Kg weight', '2.2 Kg weight', '1.8 Kg weight', '1.7 Kg weight', '1.85 Kg weight', '1.3 Kg weight (Light-weight)', '1.45 Kg weight (Light-weight)', '1.25 Kg weight (Light-weight)']

--- Colors ---
['tranquil pink', 'black', 'platinum silver', 'black', 'carbon black, platinum silver', 'natural silver', 'grey', 'black', 'quiet blue', 'black']

--- Operating System ---
['Windows 10 Home Basic', 'Windows 11 Home Basic', 'Windows 10 Home Basic', 'DOS', 'Windows 11 Home Basic', 'Windows 10 Home Basic', 'Windows 10 Home Basic', 'Windows 10 Home Basic', 'Windows 11 Home Basic', 'Windows 10 Professional']

--- Operating System Type ---
['64-bit', '64-bit', '64-bit', '64-bit', '64-bit', '64-bit', '64-bit', '64-bit', '64-bit', '64-bit']

--- Display Size ---
['14 Inches (35.56 cm)', '16 Inches (40.64 cm)', '15.6 Inches (39.62 cm)', '15.6 Inches (39.62 cm)', '15.6 Inches (39.62 cm)', '15.6 Inches (39.62 cm)', '15.6 Inches (39.62 cm)', '14 Inches (35.56 cm)', '14 Inches (35.56 cm)', '14 Inches (35.56 cm)']

--- Display Resolution ---
['1920 x 1080 Pixels', '1920 x 1200 Pixels', '1920 x 1080 Pixels', '1920 x 1080 Pixels', '1920 x 1080 Pixels', '1920 x 1080 Pixels', '1920 x 1080 Pixels', '1920 x 1080 Pixels', '2880 x 1800 Pixels', '1920 x 1080 Pixels']

--- Pixel Density ---
['157 ppi', '142 ppi', '141 ppi', '141 ppi', '141 ppi', '141 ppi', '141 ppi', '157 ppi', '243 ppi', '157 ppi']

--- Display Type ---
['LED', 'LED', 'LED', 'LED', 'LED', 'LED', 'OLED', 'LED', 'LED', 'LED']

--- Display Features ---
['full hd led backlit anti-glare ips micro-edge display   250 nits brightness   45% ntsc', 'display with ips (in-plane switching) technology   wuxga 1920 x 1200   high-brightness (400 nits) acer comfyview led-backlit tft lcd   supporting 165 hz   grey to grey 3 ms by overdrive   nvidia advanced optimus capable', 'full hd led backlit anti-glare display', 'full hd led backlit wideview anti-glare display', 'hd ag narrow border', 'diagonal   full hd micro-edge   anti-glare   220 nits   45% ntsc display', 'full hd anti-glare display', 'full hd led ips multi-touch display', 'nanoedge 2.8k oled display', 'nanoedge anti-glare led-backlit display']

--- Display Touchscreen ---
['No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'No']

--- Processor ---
['intel core i5-1135g7 (11th gen)', 'intel core i7-13700hx (13th gen)', 'intel core i5-8250u (8th gen)', 'intel core i7-7700hq (7th gen)', 'amd dual core athlon 3050u', 'amd hexa core ryzen 5 4500u', 'intel core i5-10210u (10th gen)', 'intel pentium quad core n4200', 'amd octa core ryzen 7-5800h', 'intel core i5-8250u (8th gen)']

--- Clock-speed ---
['4.2 Ghz', '1.6 Ghz', '2.8 Ghz', '2.3 Ghz', '1.6 Ghz', '2.1 Ghz', '4.2 Ghz', '3.4 Ghz', '2.4 Ghz', '2.1 Ghz']

--- Chipset ---
['intel soc', 'intel soc', 'intel', 'intel hm370 express', 'intel integrated soc', 'intel hm470', 'intel hm470', 'intel integrated soc', 'amd integrated soc', 'intel hm470']

--- Cache ---
['8 MB', '6 MB', '6 MB', '4 MB', '8 MB', '6 MB', '2 MB', '20 MB', '6 MB', '8 MB']

--- Graphic Processor ---
['intel iris x', 'nvidia geforce rtx 4050', 'amd radeon 530', 'nvidia geforce gtx 1050', 'amd radeon', 'amd radeon', 'intel integrated graphics', 'intel hd graphics', 'nvidia geforce rtx 3050', 'intel uhd 620']

--- Capacity ---
['16 GB', '16 GB', '8 GB', '8 GB', '4 GB', '8 GB', '8 GB', '4 GB', '16 GB', '8 GB']

--- RAM Type ---
['DDR4', 'DDR5', 'DDR4', 'DDR4', 'DDR4', 'DDR4', 'DDR4', 'DDR3', 'DDR4', 'DDR4']

--- RAM Speed ---
['3200 Mhz', '2400 Mhz', '2400 Mhz', '2666 Mhz', '2666 Mhz', '1600 Mhz', '3200 Mhz', '2133 Mhz', '3200 Mhz', '2400 Mhz']

--- Memory Slots ---
['2', '1', '1', '1', '1', '1', '1', '1', '1', '1']

--- Memory Layout ---
['2x8 gigabyte', '1*16 gigabyte', '1 x 8 gigabyte', '1x8 gigabyte', '1x8 gigabyte', '1x8 gigabyte', '1x4 gigabyte', '1*16 gigabyte', '1 x 8 gigabyte', '1x8 gigabyte']

--- SSD Capacity ---
['512 GB', '512 GB', '256 GB', '256 GB', '32 GB', '512 GB', '256 GB', '512 GB', '512 GB', '512 GB']

--- SSD Type ---
['M.2/Optane', 'M.2', 'M.2/Optane', 'M.2', 'M.2', 'M.2/Optane', 'M.2', 'M.2', 'M.2/Optane', 'M.2/Optane']

--- Battery Cell ---
['3 Cell', '4 Cell', '3 Cell', '6 Cell', '3 Cell', '3 Cell', '2 Cell', '3 Cell', '3 Cell', '3 Cell']

--- Battery Type ---
['Li-Ion', 'Li-Ion', 'Li-Ion', 'Li-Ion', 'Li-Ion', 'Li-Po', 'Li-Po', 'Li-Po', 'Li-Po', 'Li-Ion']

--- Power Supply ---
['43 w ac adapter w', '230 w', '42 w ac adapter w', '65 w', '65 w ac adapter w', '38 w ac adapter w', '65 w', '50 w ac adapter w', '65 w ac adapter w', '45 w ac adapter w']

--- Wireless LAN ---
['802.11 b/g/n/ax', '802.11 a/b/g/n/ac', '802.11 a/b/g/n/ac', '802.11 a/b/g/n/ac', '802.11 a/b/g/n/ac', '802.11 a/b/g/n/ac', '802.11 a/b/g/n/ac', '802.11 a/b/g/n/ac', '802.11 b/g/n/ax', '802.11 a/b/g/n/ac']

--- Bluetooth ---
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']

--- HDMI Ports ---
['1', '1', '1', '1', '1', '1', '1', '1', '1', '1']

--- SD Card Reader ---
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']

--- Headphone Jack ---
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']

--- Microphone Jack ---
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']

--- Web-cam ---
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']

--- Video Recording ---
['720p hd', '720p', 'hd 720p', '720p hd', '720p hd', '720p hd', '720p hd', '720', 'hd 720p', '720p hd']

--- Speakers ---
['dual speakers', 'stereo speakers', 'stereo speakers', 'quad speakers', 'built-in speakers', 'dual speakers', 'dual speakers', 'dual speakers', 'built-in speaker', 'dual speakers']

--- In-built Microphone ---
['Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes']

--- Microphone Type ---
['dual array digital microphone', 'built-in microphones', 'dual array digital microphone', 'digital microphone', 'integrated dual array digital microphone', 'built-in microphone', 'internal microphone', 'dual array digital microphone with cortana voice-recognition support', 'built-in dual array microphone', 'built-in array microphone']

--- Pointing device ---
['touchpad with multi-touch gesture support', 'multi-gesture touchpad, supporting two-finger scroll; pinch; gestures to open cortana, action center, multitasking; application commands', 'touchpad with multi-touch gesture support', 'touchpad with multi-touch gestures enabled', 'touchpad', 'touchpad with multi-touch gestures enabled', 'touchpad with multi-touch gestures enabled', 'touchpad with multi-touch gestures enabled', 'precision touchpad (ptp) technology supports up to four-finger smart gestures', 'touchpad with multi-touch gestures enabled']

--- Keyboard ---
['standard notebook keyboard', '103-/104-/107-key finetip rgb- keyboard with independent standard numeric keypad, international language support', 'standard notebook keyboard', 'steelseries gaming backlight keyboard (red color)', 'english international non keyboard', 'standard notebook keyboard', 'standard notebook keyboard', 'standard notebook keyboard', 'full-size , with 1.4mm key travel', 'standard english keyboard']

--- Fingerprint scanner ---
['No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'No']

--- Warranty ---
['1 Year', '1 Year', '1 Year', '1 Year', '1 Year', '1 Year', '1 Year', '1 Year', '1 Year', '1 Year']

--- Sales Package ---
['laptop, battery, ac adapter, user guide', 'laptop, power adaptor, user guide, warranty documents', 'laptop, battery, ac adapter, user guide', 'laptop, battery, ac adapter, user guide', 'laptop, battery, adapter, cables and user manuals', 'laptop, battery, ac adapter, user guide', 'laptop, battery, ac adapter, user guide', 'laptop, battery, ac adapter, user guide', 'laptop, power adaptor, user guide, warranty documents', 'laptop, battery, ac adapter, user guide']

--- Refresh Rate ---
['165 Hz', '90 Hz', '120 Hz', '144 Hz', '60 Hz', '144 Hz', '60 Hz', '144 Hz', '144 Hz', '60 Hz']

--- Brightness ---
['400 nits', '250 nits', '250 nits', '300 nits', '250 nits', '500 nits', '250 nits', '250 nits', '300 nits', '250 nits']

--- Graphics Memory ---
['6 GB', '2 GB', '4 GB', '4 GB', '2 GB', '4 GB', '2 GB', '4 GB', '8 GB', '8 GB']

--- Expandable Memory ---
['32 GB', '32 GB', '32 GB', '16 GB', '12 GB', '16 GB', '32 GB', '12 GB', '32 GB', '32 GB']

--- Backlit Keyboard ---
['yes, 103-/104-/107-key finetip rgb-backlit keyboard with independent standard numeric keypad, international language support', 'yes, english international non backlit keyboard', 'yes, full-size backlit, with 1.4mm key travel', 'yes, standard english backlit keyboard', 'yes, backlit chiclet keyboard', 'yes, backlit keyboard', 'yes, blue led backlit, english keyboard', 'yes, backlit english keyboard', 'yes, rgb backlit gaming keyboard', 'yes, finetip backlit keyboard with independent standard numeric keypad (international language support)']

--- HDD Capacity ---
['2 TB', '1 TB', '1 TB', '1 TB', '1 TB', '1 TB', '1 TB', '1 TB', '1 TB', '1 TB']

--- HDD Speed(RPM) ---
['5400 RPM', '5400 RPM', '5400 RPM', '5400 RPM', '7200 RPM', '5400 RPM', '5400 RPM', '5400 RPM', '5400 RPM', '5400 RPM']

--- HDD Type ---
['SATA', 'SATA', 'SATA', 'SATA', 'SATA', 'SATA', 'SATA', 'SATA', 'SATA', 'SATA']

--- Battery Life ---
['7 Hrs', '8 Hrs', '9 Hrs', '7.5 Hrs', '7 Hrs', '6 Hrs', '5 Hrs', '6 Hrs', '8 Hrs', '6 Hrs']

--- Battery Capacity ---
['63 WHrs', '41 WHrs', '52.6 WHrs', '45 WHrs', '35 WHrs', '40 WHrs', '56 WHrs', '56 WHrs', '40 WHrs', '45 WHrs']

--- Aspect Ratio ---
['16:9', '16:9', '16:10', '16:9', '16:9', '16:9', '16:9', '16:9', '16:10', '16:10']

--- SSD Interface ---
['NVMe PCIe', 'PCIe', 'NVMe PCIe', 'NVMe PCIe', 'NVMe', 'NVMe PCIe', 'NVMe PCIe', 'NVMe PCIe', 'NVMe PCIe', 'NVMe PCIe']

--- market_status ---
['Available', 'Available', 'Available', 'Available', 'Available', 'Available', 'Available', 'Available', 'Available', 'Available']

In [40]:
# Direct Numeric Extraction

measurement_columns = [
    "Thickness",
    "Weight",
    "Display Size",
    "Pixel Density",
    "Clock-speed",
    "Cache",
    "RAM Speed",
    "SSD Capacity",
    "Battery Cell",
    "Power Supply",
    "Refresh Rate",
    "Brightness",
    "Graphics Memory",
    "Expandable Memory",
    "HDD Capacity",
    "HDD Speed(RPM)",
    "Battery Life",
    "Battery Capacity"
]

In [41]:
df[measurement_columns].head(10)

,Thickness,Weight,Display Size,Pixel Density,Clock-speed,Cache,RAM Speed,SSD Capacity,Battery Cell,Power Supply,Refresh Rate,Brightness,Graphics Memory,Expandable Memory,HDD Capacity,HDD Speed(RPM),Battery Life,Battery Capacity
0,17 Millimeter thickness,1.41 Kg weight (Light-weight),14 Inches (35.56 cm),157 ppi,4.2 Ghz,8 MB,3200 Mhz,512 GB,3 Cell,43 w ac adapter w,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26.5 Millimeter thickness,2.6 Kg weight,16 Inches (40.64 cm),142 ppi,NaN,NaN,NaN,512 GB,4 Cell,230 w,165 Hz,400 nits,6 GB,32 GB,NaN,NaN,NaN,NaN
2,22.7 Millimeter thickness,2.2 Kg weight,15.6 Inches (39.62 cm),141 ppi,1.6 Ghz,6 MB,2400 Mhz,NaN,3 Cell,42 w ac adapter w,NaN,NaN,2 GB,32 GB,2 TB,5400 RPM,NaN,NaN
3,29 Millimeter thickness,2.2 Kg weight,15.6 Inches (39.62 cm),141 ppi,2.8 Ghz,6 MB,2400 Mhz,NaN,6 Cell,<NA>,NaN,NaN,4 GB,32 GB,1 TB,5400 RPM,NaN,NaN
4,23 Millimeter thickness,1.8 Kg weight,15.6 Inches (39.62 cm),141 ppi,NaN,4 MB,2666 Mhz,256 GB,3 Cell,65 w,NaN,NaN,NaN,NaN,NaN,NaN,7 Hrs,NaN
5,17.9 Millimeter thickness,1.7 Kg weight,15.6 Inches (39.62 cm),141 ppi,2.3 Ghz,8 MB,2666 Mhz,256 GB,3 Cell,65 w ac adapter w,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,19.9 Millimeter thickness,1.85 Kg weight,15.6 Inches (39.62 cm),141 ppi,1.6 Ghz,6 MB,NaN,NaN,2 Cell,<NA>,NaN,NaN,NaN,NaN,1 TB,5400 RPM,NaN,NaN
7,24 Millimeter thickness,1.3 Kg weight (Light-weight),14 Inches (35.56 cm),157 ppi,2.1 Ghz,2 MB,1600 Mhz,32 GB,NaN,38 w ac adapter w,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,19 Millimeter thickness,1.45 Kg weight (Light-weight),14 Inches (35.56 cm),243 ppi,4.2 Ghz,20 MB,3200 Mhz,512 GB,3 Cell,65 w,90 Hz,NaN,4 GB,16 GB,NaN,NaN,8 Hrs,63 WHrs
9,15.9 Millimeter thickness (Slim),1.25 Kg weight (Light-weight),14 Inches (35.56 cm),157 ppi,3.4 Ghz,6 MB,2133 Mhz,256 GB,3 Cell,50 w ac adapter w,NaN,NaN,NaN,NaN,NaN,NaN,9 Hrs,NaN

In [42]:
for column in measurement_columns:
    df[column] = (
        df[column]
        .astype("string")
        .str.extract(r"([-+]?\d*\.?\d+)", expand=False)
        .astype(float)
    )

In [43]:
df[measurement_columns].head(10)

,Thickness,Weight,Display Size,Pixel Density,Clock-speed,Cache,RAM Speed,SSD Capacity,Battery Cell,Power Supply,Refresh Rate,Brightness,Graphics Memory,Expandable Memory,HDD Capacity,HDD Speed(RPM),Battery Life,Battery Capacity
0,17.0,1.41,14.0,157.0,4.2,8.0,3200.0,512.0,3.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26.5,2.60,16.0,142.0,NaN,NaN,NaN,512.0,4.0,230.0,165.0,400.0,6.0,32.0,NaN,NaN,NaN,NaN
2,22.7,2.20,15.6,141.0,1.6,6.0,2400.0,NaN,3.0,42.0,NaN,NaN,2.0,32.0,2.0,5400.0,NaN,NaN
3,29.0,2.20,15.6,141.0,2.8,6.0,2400.0,NaN,6.0,NaN,NaN,NaN,4.0,32.0,1.0,5400.0,NaN,NaN
4,23.0,1.80,15.6,141.0,NaN,4.0,2666.0,256.0,3.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN
5,17.9,1.70,15.6,141.0,2.3,8.0,2666.0,256.0,3.0,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,19.9,1.85,15.6,141.0,1.6,6.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,5400.0,NaN,NaN
7,24.0,1.30,14.0,157.0,2.1,2.0,1600.0,32.0,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,19.0,1.45,14.0,243.0,4.2,20.0,3200.0,512.0,3.0,65.0,90.0,NaN,4.0,16.0,NaN,NaN,8.0,63.0
9,15.9,1.25,14.0,157.0,3.4,6.0,2133.0,256.0,3.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN

In [44]:
df[measurement_columns].dtypes

Thickness            float64
Weight               float64
Display Size         float64
Pixel Density        float64
Clock-speed          float64
Cache                float64
RAM Speed            float64
SSD Capacity         float64
Battery Cell         float64
Power Supply         float64
Refresh Rate         float64
Brightness           float64
Graphics Memory      float64
Expandable Memory    float64
HDD Capacity         float64
HDD Speed(RPM)       float64
Battery Life         float64
Battery Capacity     float64
dtype: object

# Final Data Quality Check

In [45]:
df.dtypes

Brand                     str
Model                     str
Series                    str
Thickness             float64
Dimensions (WxDxH)        str
                       ...
Aspect Ratio              str
Number of Cores       float64
SSD Interface             str
market_status             str
Price (Rs)            float64
Length: 67, dtype: object

In [46]:
print("Final shape:", df.shape)
print(df.dtypes.value_counts())
print(df["Price (Rs)"].dtype)
print(df.columns.tolist())

Final shape: (8176, 67)
str        26
float64    26
string     13
object      2
Name: count, dtype: int64
float64
['Brand', 'Model', 'Series', 'Thickness', 'Dimensions (WxDxH)', 'Weight', 'Colors', 'Operating System', 'Operating System Type', 'Display Size', 'Display Resolution', 'Pixel Density', 'Display Type', 'Display Features', 'Display Touchscreen', 'Processor', 'Clock-speed', 'Chipset', 'Cache', 'Graphic Processor', 'Capacity', 'RAM Type', 'RAM Speed', 'Memory Slots', 'Memory Layout', 'SSD Capacity', 'SSD Type', 'Battery Cell', 'Battery Type', 'Power Supply', 'Wireless LAN', 'Wi-Fi Version', 'Bluetooth', 'Bluetooth Version', 'HDMI Ports', 'USB 2.0 slots', 'SD Card Reader', 'Ethernet ports', 'Headphone Jack', 'Microphone Jack', 'Web-cam', 'Video Recording', 'Speakers', 'In-built Microphone', 'Microphone Type', 'Pointing device', 'Keyboard', 'Fingerprint scanner', 'Warranty', 'Sales Package', 'Refresh Rate', 'Brightness', 'Graphics Memory', 'Expandable Memory', 'Backlit Keyboard', 'HDD Capacity', 'HDD Speed(RPM)', 'HDD Type', 'USB 3.0 slots', 'Battery Life', 'USB Type C', 'Battery Capacity', 'Aspect Ratio', 'Number of Cores', 'SSD Interface', 'market_status', 'Price (Rs)']

In [47]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [48]:
missing_summary = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": df.isna().mean() * 100
})

missing_summary = missing_summary[missing_summary["Missing Count"] > 0]

missing_summary.sort_values(
    "Missing Percentage",
    ascending=False
)

                       Missing Count  Missing Percentage
Chipset                         7133           87.243151
Aspect Ratio                    6849           83.769569
HDD Type                        6448           78.864971
HDD Speed(RPM)                  6440           78.767123
HDD Capacity                    6323           77.336106
SSD Interface                   6128           74.951076
USB 3.0 slots                   5955           72.835127
Brightness                      5807           71.024951
Battery Capacity                5732           70.107632
SSD Type                        5729           70.070939
Battery Life                    5457           66.744129
Number of Cores                 5259           64.322407
Graphics Memory                 5111           62.512231
Refresh Rate                    5069           61.998532
USB 2.0 slots                   4952           60.567515
Expandable Memory               4948           60.518591
Ethernet ports                  4741           57.986791
Display Type                    3876           47.407045
SD Card Reader                  3700           45.254403
Backlit Keyboard                3590           43.909002
Operating System Type           3504           42.857143
RAM Speed                       3082           37.695695
USB Type C                      3005           36.753914
Fingerprint scanner             2674           32.705479
Pointing device                 2311           28.265656
Cache                           1560           19.080235
Power Supply                    1414           17.294521
SSD Capacity                    1333           16.303816
Battery Cell                    1300           15.900196
Video Recording                 1151           14.077789
Series                          1090           13.331703
Keyboard                        1074           13.136008
Bluetooth Version                815            9.968200
HDMI Ports                       755            9.234344
Battery Type                     729            8.916341
Dimensions (WxDxH)               680            8.317025
Thickness                        678            8.292564
Clock-speed                      467            5.711840
Warranty                         446            5.454990
Weight                           306            3.742661
Web-cam                          271            3.314579
Microphone Type                  235            2.874266
In-built Microphone              185            2.262720
Colors                           176            2.152642
RAM Type                         170            2.079256
Memory Layout                    155            1.895793
Display Features                 131            1.602250
Speakers                         109            1.333170
Graphic Processor                 92            1.125245
Display Touchscreen               82            1.002935
Wi-Fi Version                     74            0.905088
Wireless LAN                      74            0.905088
Memory Slots                      63            0.770548
Bluetooth                         48            0.587084
Pixel Density                     34            0.415851
Display Resolution                32            0.391389
Microphone Jack                   16            0.195695
Headphone Jack                    14            0.171233
Sales Package                     14            0.171233
Display Size                       3            0.036693

In [49]:
print("total no columns having missing values :", len(missing_summary))
df.isna().sum().sort_values(ascending=False).head(20)

total no columns having missing values : 60

Chipset              7133
Aspect Ratio         6849
HDD Type             6448
HDD Speed(RPM)       6440
HDD Capacity         6323
SSD Interface        6128
USB 3.0 slots        5955
Brightness           5807
Battery Capacity     5732
SSD Type             5729
Battery Life         5457
Number of Cores      5259
Graphics Memory      5111
Refresh Rate         5069
USB 2.0 slots        4952
Expandable Memory    4948
Ethernet ports       4741
Display Type         3876
SD Card Reader       3700
Backlit Keyboard     3590
dtype: int64