In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/laptop_cleaned.csv")

In [2]:
print("Shape:", df.shape)

Shape: (8176, 67)

In [3]:
print("Number of columns:", len(df.columns))
print(df.columns.tolist())

Number of columns: 67
['Brand', 'Model', 'Series', 'Thickness', 'Dimensions (WxDxH)', 'Weight', 'Colors', 'Operating System', 'Operating System Type', 'Display Size', 'Display Resolution', 'Pixel Density', 'Display Type', 'Display Features', 'Display Touchscreen', 'Processor', 'Clock-speed', 'Chipset', 'Cache', 'Graphic Processor', 'Capacity', 'RAM Type', 'RAM Speed', 'Memory Slots', 'Memory Layout', 'SSD Capacity', 'SSD Type', 'Battery Cell', 'Battery Type', 'Power Supply', 'Wireless LAN', 'Wi-Fi Version', 'Bluetooth', 'Bluetooth Version', 'HDMI Ports', 'USB 2.0 slots', 'SD Card Reader', 'Ethernet ports', 'Headphone Jack', 'Microphone Jack', 'Web-cam', 'Video Recording', 'Speakers', 'In-built Microphone', 'Microphone Type', 'Pointing device', 'Keyboard', 'Fingerprint scanner', 'Warranty', 'Sales Package', 'Refresh Rate', 'Brightness', 'Graphics Memory', 'Expandable Memory', 'Backlit Keyboard', 'HDD Capacity', 'HDD Speed(RPM)', 'HDD Type', 'USB 3.0 slots', 'Battery Life', 'USB Type C', 'Battery Capacity', 'Aspect Ratio', 'Number of Cores', 'SSD Interface', 'market_status', 'Price (Rs)']

In [4]:
target = "Price (Rs)"
print("Target dtype:", df[target].dtype)
print("Missing target values:", df[target].isna().sum())

Target dtype: float64
Missing target values: 0

In [5]:
print(df.dtypes.value_counts())

str        41
float64    26
Name: count, dtype: int64

In [6]:
missing = df.isna().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)
print("no of columns with missing values",len(missing))

Chipset                  7133
Aspect Ratio             6849
HDD Type                 6448
HDD Speed(RPM)           6440
HDD Capacity             6323
SSD Interface            6128
USB 3.0 slots            5955
Brightness               5807
Battery Capacity         5732
SSD Type                 5729
Battery Life             5457
Number of Cores          5259
Graphics Memory          5111
Refresh Rate             5069
USB 2.0 slots            4952
Expandable Memory        4948
Ethernet ports           4741
Display Type             3876
SD Card Reader           3700
Backlit Keyboard         3590
Operating System Type    3504
RAM Speed                3082
USB Type C               3005
Fingerprint scanner      2674
Pointing device          2311
Cache                    1560
Power Supply             1414
SSD Capacity             1333
Battery Cell             1300
Video Recording          1151
Series                   1090
Keyboard                 1074
Bluetooth Version         815
HDMI Ports                755
Battery Type              729
Dimensions (WxDxH)        680
Thickness                 678
Clock-speed               467
Warranty                  446
Weight                    306
Web-cam                   271
Microphone Type           235
In-built Microphone       185
Colors                    176
RAM Type                  170
Memory Layout             155
Display Features          131
Speakers                  109
Graphic Processor          92
Display Touchscreen        82
Wi-Fi Version              74
Wireless LAN               74
Memory Slots               63
Bluetooth                  48
Pixel Density              34
Display Resolution         32
Microphone Jack            16
Headphone Jack             14
Sales Package              14
Display Size                3
dtype: int64
no of columns with missing values 60

In [7]:
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

# Complete Feature Inventory

In [8]:
feature_inventory = pd.DataFrame({
    "Feature": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Unique Values": df.nunique(dropna=True),
    "Missing Count": df.isna().sum(),
    "Missing %": (df.isna().mean() * 100).round(2)
})

feature_inventory = feature_inventory[
    feature_inventory["Feature"] != "Price (Rs)"
].reset_index(drop=True)

print("Number of candidate features:", len(feature_inventory))
feature_inventory

Number of candidate features: 66

               Feature Data Type  Unique Values  Missing Count  Missing %
0                Brand       str             35              0       0.00
1                Model       str           8116              0       0.00
2               Series       str            532           1090      13.33
3            Thickness   float64            256            678       8.29
4   Dimensions (WxDxH)       str           2274            680       8.32
..                 ...       ...            ...            ...        ...
61    Battery Capacity   float64             89           5732      70.11
62        Aspect Ratio       str              3           6849      83.77
63     Number of Cores   float64             12           5259      64.32
64       SSD Interface       str              4           6128      74.95
65       market_status       str              2              0       0.00

[66 rows x 5 columns]

In [9]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

display(feature_inventory)

                  Feature Data Type  Unique Values  Missing Count  Missing %
0                   Brand       str             35              0       0.00
1                   Model       str           8116              0       0.00
2                  Series       str            532           1090      13.33
3               Thickness   float64            256            678       8.29
4      Dimensions (WxDxH)       str           2274            680       8.32
5                  Weight   float64            228            306       3.74
6                  Colors       str            470            176       2.15
7        Operating System       str             32              0       0.00
8   Operating System Type       str              2           3504      42.86
9            Display Size   float64             37              3       0.04
10     Display Resolution       str             57             32       0.39
11          Pixel Density   float64            112             34       0.42
12           Display Type       str             11           3876      47.41
13       Display Features       str           3245            131       1.60
14    Display Touchscreen       str              2             82       1.00
15              Processor       str            731              0       0.00
16            Clock-speed   float64             48            467       5.71
17                Chipset       str             58           7133      87.24
18                  Cache   float64             30           1560      19.08
19      Graphic Processor       str            334             92       1.13
20               Capacity       str             14              0       0.00
21               RAM Type       str             10            170       2.08
22              RAM Speed   float64             43           3082      37.70
23           Memory Slots       str             15             63       0.77
24          Memory Layout       str             72            155       1.90
25           SSD Capacity   float64             11           1333      16.30
26               SSD Type       str              2           5729      70.07
27           Battery Cell   float64              8           1300      15.90
28           Battery Type       str              2            729       8.92
29           Power Supply   float64             98           1414      17.29
30           Wireless LAN       str              6             74       0.91
31          Wi-Fi Version   float64              4             74       0.91
32              Bluetooth       str              2             48       0.59
33      Bluetooth Version   float64             11            815       9.97
34             HDMI Ports       str              7            755       9.23
35          USB 2.0 slots   float64              3           4952      60.57
36         SD Card Reader       str              2           3700      45.25
37         Ethernet ports   float64              2           4741      57.99
38         Headphone Jack       str              2             14       0.17
39        Microphone Jack       str              2             16       0.20
40                Web-cam       str              2            271       3.31
41        Video Recording       str             27           1151      14.08
42               Speakers       str            221            109       1.33
43    In-built Microphone       str              2            185       2.26
44        Microphone Type       str            176            235       2.87
45        Pointing device       str            269           2311      28.27
46               Keyboard       str            807           1074      13.14
47    Fingerprint scanner       str              6           2674      32.71
48               Warranty       str             13            446       5.45
49          Sales Package       str             74             14       0.17
50           Refresh Rate   float64             12           5069      62.00
51             Brightness   float64             21           5807      71.02
52        Graphics Memory   float64             11           5111      62.51
53      Expandable Memory   float64             12           4948      60.52
54       Backlit Keyboard       str            528           3590      43.91
55           HDD Capacity   float64              4           6323      77.34
56         HDD Speed(RPM)   float64              2           6440      78.77
57               HDD Type       str              1           6448      78.86
58          USB 3.0 slots   float64              6           5955      72.84
59           Battery Life   float64            113           5457      66.74
60             USB Type C   float64              4           3005      36.75
61       Battery Capacity   float64             89           5732      70.11
62           Aspect Ratio       str              3           6849      83.77
63        Number of Cores   float64             12           5259      64.32
64          SSD Interface       str              4           6128      74.95
65          market_status       str              2              0       0.00

# feature engineering

In [10]:
print(df["Capacity"].value_counts(dropna=False))

Capacity
8 GB      3301
16 GB     3122
4 GB      1159
32 GB      421
24 GB       57
2 GB        38
64 GB       29
12 GB       22
36 GB       10
48 GB        6
18 GB        6
3 GB         2
6 GB         2
128 GB       1
Name: count, dtype: int64

In [11]:
print(
    df["Capacity"]
    .astype(str)
    .str.match(r"^\d+(\.\d+)?\s*GB$", case=False)
    .value_counts()
)

Capacity
True    8176
Name: count, dtype: int64

In [12]:
feature_decisions = {

    # ============================================================
    # Group 1 — Identity / administrative
    # ============================================================

    "Brand": "KEEP",
    "Model": "REMOVE",
    "Series": "KEEP",
    "Warranty": "REMOVE",
    "Sales Package": "REMOVE",
    "market_status": "REMOVE",

    # ============================================================
    # Group 2 — Physical characteristics
    # ============================================================

    "Thickness": "KEEP",
    "Dimensions (WxDxH)": "REMOVE",
    "Weight": "KEEP",
    "Colors": "REMOVE",

    # ============================================================
    # Group 3 — Operating system
    # ============================================================

    "Operating System": "KEEP",
    "Operating System Type": "REMOVE",

    # ============================================================
    # Group 4 — Display
    # ============================================================

    "Display Size": "KEEP",
    "Display Resolution": "REMOVE",
    "Pixel Density": "REMOVE",
    "Display Type": "REMOVE",
    "Display Features": "REMOVE",
    "Display Touchscreen": "KEEP",

    # ============================================================
    # Group 5 — Processor
    # ============================================================

    "Processor": "KEEP",
    "Clock-speed": "REMOVE",
    "Chipset": "REMOVE",
    "Cache": "REMOVE",
    "Number of Cores": "REMOVE",

    # ============================================================
    # Group 6 — GPU
    # ============================================================

    "Graphic Processor": "KEEP",
    "Graphics Memory": "REMOVE",

    # ============================================================
    # Group 7 — RAM
    # ============================================================

    "Capacity": "TRANSFORM",
    "RAM Type": "KEEP",
    "RAM Speed": "REMOVE",
    "Memory Slots": "REMOVE",
    "Memory Layout": "REMOVE",
    "Expandable Memory": "REMOVE",

    # ============================================================
    # Group 8 — Storage
    # ============================================================

    "SSD Capacity": "KEEP",
    "SSD Type": "REMOVE",
    "SSD Interface": "REMOVE",
    "HDD Capacity": "KEEP",
    "HDD Speed(RPM)": "REMOVE",
    "HDD Type": "REMOVE",

    # ============================================================
    # Group 9 — Battery
    # ============================================================

    "Battery Cell": "REMOVE",
    "Battery Type": "REMOVE",
    "Battery Life": "REMOVE",
    "Battery Capacity": "KEEP",

    # ============================================================
    # Group 10 — Connectivity / ports
    # ============================================================

    "Wireless LAN": "REMOVE",
    "Wi-Fi Version": "REMOVE",
    "Bluetooth": "REMOVE",
    "Bluetooth Version": "REMOVE",
    "HDMI Ports": "REMOVE",
    "USB 2.0 slots": "REMOVE",
    "USB 3.0 slots": "REMOVE",
    "USB Type C": "REMOVE",
    "Ethernet ports": "REMOVE",
    "SD Card Reader": "REMOVE",
    "Headphone Jack": "REMOVE",
    "Microphone Jack": "REMOVE",

    # ============================================================
    # Group 11 — Camera / audio / input
    # ============================================================

    "Web-cam": "REMOVE",
    "Video Recording": "REMOVE",
    "Speakers": "REMOVE",
    "In-built Microphone": "REMOVE",
    "Microphone Type": "REMOVE",
    "Pointing device": "REMOVE",
    "Keyboard": "REMOVE",
    "Backlit Keyboard": "REMOVE",
    "Fingerprint scanner": "KEEP",

    # ============================================================
    # Remaining original predictors
    # ============================================================

    "Power Supply": "REMOVE",
    "Refresh Rate": "REMOVE",
    "Brightness": "REMOVE",
    "Graphics Memory": "REMOVE",
    "Aspect Ratio": "REMOVE",
    "Battery Life": "REMOVE",
    "USB Type C": "REMOVE",
}

In [13]:
predictor_columns = [
    col for col in df.columns
    if col != "Price (Rs)"
]

print("Original predictor count:", len(predictor_columns))
print("Decision dictionary count:", len(feature_decisions))

Original predictor count: 66
Decision dictionary count: 66

In [14]:
for decision in ["KEEP", "TRANSFORM", "ENGINEER", "REMOVE"]:

    selected = [
        col
        for col, value in feature_decisions.items()
        if value == decision
    ]

    print(f"\n{decision} ({len(selected)}):")

    for col in selected:
        print(" -", col)

KEEP (14):
 - Brand
 - Series
 - Thickness
 - Weight
 - Operating System
 - Display Size
 - Display Touchscreen
 - Processor
 - Graphic Processor
 - RAM Type
 - SSD Capacity
 - HDD Capacity
 - Battery Capacity
 - Fingerprint scanner

TRANSFORM (1):
 - Capacity

ENGINEER (0):

REMOVE (51):
 - Model
 - Warranty
 - Sales Package
 - market_status
 - Dimensions (WxDxH)
 - Colors
 - Operating System Type
 - Display Resolution
 - Pixel Density
 - Display Type
 - Display Features
 - Clock-speed
 - Chipset
 - Cache
 - Number of Cores
 - Graphics Memory
 - RAM Speed
 - Memory Slots
 - Memory Layout
 - Expandable Memory
 - SSD Type
 - SSD Interface
 - HDD Speed(RPM)
 - HDD Type
 - Battery Cell
 - Battery Type
 - Battery Life
 - Wireless LAN
 - Wi-Fi Version
 - Bluetooth
 - Bluetooth Version
 - HDMI Ports
 - USB 2.0 slots
 - USB 3.0 slots
 - USB Type C
 - Ethernet ports
 - SD Card Reader
 - Headphone Jack
 - Microphone Jack
 - Web-cam
 - Video Recording
 - Speakers
 - In-built Microphone
 - Microphone Type
 - Pointing device
 - Keyboard
 - Backlit Keyboard
 - Power Supply
 - Refresh Rate
 - Brightness
 - Aspect Ratio

In [15]:
df["Capacity"]

0        16 GB
1        16 GB
2         8 GB
3         8 GB
4         4 GB
5         8 GB
6         8 GB
7         4 GB
8        16 GB
9         8 GB
10        8 GB
11        4 GB
12        8 GB
13        8 GB
14        4 GB
15        8 GB
16        8 GB
17        8 GB
18        8 GB
19       16 GB
20        8 GB
21        8 GB
22        8 GB
23       16 GB
24       16 GB
25        8 GB
26        4 GB
27        8 GB
28        8 GB
29        8 GB
30        8 GB
31        8 GB
32        8 GB
33        8 GB
34        8 GB
35        4 GB
36        8 GB
37        8 GB
38        8 GB
39        4 GB
40        8 GB
41        8 GB
42       16 GB
43        8 GB
44        4 GB
45        8 GB
46       16 GB
47        8 GB
48        8 GB
49       16 GB
50       16 GB
51        8 GB
52        8 GB
53        8 GB
54        8 GB
55       16 GB
56        8 GB
57        8 GB
58        8 GB
59       16 GB
60        4 GB
61       16 GB
62        8 GB
63        4 GB
64        4 GB
65        8 GB
66       16 GB
67        8 GB
68        8 GB
69        8 GB
70       16 GB
71        4 GB
72        4 GB
73        8 GB
74       16 GB
75        8 GB
76        8 GB
77        8 GB
78        8 GB
79        8 GB
80        4 GB
81        8 GB
82        8 GB
83        8 GB
84        8 GB
85        4 GB
86       16 GB
87        8 GB
88        8 GB
89        8 GB
90       16 GB
91        8 GB
92       16 GB
93        8 GB
94        8 GB
95        8 GB
96        8 GB
97        8 GB
98        8 GB
99        8 GB
100      16 GB
101       8 GB
102       8 GB
103      16 GB
104      16 GB
105       8 GB
106      16 GB
107       8 GB
108       4 GB
109       8 GB
110       8 GB
111       8 GB
112       8 GB
113       8 GB
114       8 GB
115       4 GB
116       4 GB
117       8 GB
118       8 GB
119       8 GB
120       8 GB
121       4 GB
122      16 GB
123       8 GB
124       8 GB
125       8 GB
126       8 GB
127      16 GB
128      16 GB
129       8 GB
130       8 GB
131       4 GB
132       8 GB
133       4 GB
134       4 GB
135      16 GB
136       8 GB
137       4 GB
138       8 GB
139       4 GB
140       4 GB
141       8 GB
142       8 GB
143       8 GB
144       8 GB
145       8 GB
146       8 GB
147      16 GB
148       8 GB
149      16 GB
150       8 GB
151       4 GB
152      16 GB
153       8 GB
154       8 GB
155      32 GB
156      16 GB
157       8 GB
158       8 GB
159       8 GB
160       8 GB
161       8 GB
162       8 GB
163       4 GB
164       8 GB
165       8 GB
166       8 GB
167       4 GB
168       4 GB
169       8 GB
170       8 GB
171       8 GB
172       8 GB
173       8 GB
174      16 GB
175       8 GB
176       8 GB
177       8 GB
178       8 GB
179       4 GB
180       8 GB
181       4 GB
182       8 GB
183       8 GB
184       8 GB
185      16 GB
186       8 GB
187      16 GB
188       8 GB
189       8 GB
190       8 GB
191      16 GB
192       8 GB
193       4 GB
194       8 GB
195       8 GB
196       4 GB
197       8 GB
198       8 GB
199       8 GB
200       4 GB
201      16 GB
202       8 GB
203      16 GB
204       8 GB
205       4 GB
206       8 GB
207       4 GB
208       8 GB
209       2 GB
210       4 GB
211       4 GB
212       4 GB
213       4 GB
214       8 GB
215       2 GB
216       4 GB
217      16 GB
218       4 GB
219       4 GB
220       4 GB
221       2 GB
222      16 GB
223      16 GB
224       8 GB
225       4 GB
226       4 GB
227       8 GB
228       8 GB
229       4 GB
230       8 GB
231       8 GB
232       8 GB
233      16 GB
234       4 GB
235       8 GB
236       2 GB
237       4 GB
238       4 GB
239       4 GB
240       4 GB
241       4 GB
242      16 GB
243      16 GB
244      16 GB
245       4 GB
246       4 GB
247      16 GB
248       8 GB
249       4 GB
250       4 GB
251       8 GB
252       4 GB
253      16 GB
254       8 GB
255       8 GB
256      16 GB
257       2 GB
258       8 GB
259       8 GB
260       4 GB
261       4 GB
262       8 GB
263       4 GB
264       4 GB
265      16 GB
266       8 GB
267       4 GB
268       8 GB
269      16 GB
270      16 GB
271      16 GB
272       2 GB
273       8 GB
274       8 GB
275      16 GB
276       4 GB
277       4 GB
278       8 GB
279       8 GB
280      16 GB
281       4 GB
282       8 GB
283       2 GB
284      16 GB
285      32 GB
286      16 GB
287      16 GB
288      16 GB
289      16 GB
290      16 GB
291      16 GB
292      64 GB
293       8 GB
294       4 GB
295       4 GB
296      16 GB
297       4 GB
298       8 GB
299      16 GB
300      16 GB
301       2 GB
302      16 GB
303      16 GB
304       4 GB
305       4 GB
306      16 GB
307      16 GB
308      16 GB
309       4 GB
310      32 GB
311       4 GB
312       8 GB
313       4 GB
314       8 GB
315      32 GB
316      16 GB
317      16 GB
318      32 GB
319      16 GB
320       8 GB
321       8 GB
322       8 GB
323       4 GB
324       4 GB
325       4 GB
326      32 GB
327       8 GB
328      16 GB
329       8 GB
330       8 GB
331      32 GB
332      16 GB
333      16 GB
334      16 GB
335       8 GB
336      32 GB
337       4 GB
338      16 GB
339      16 GB
340      16 GB
341       4 GB
342       8 GB
343      16 GB
344      16 GB
345       4 GB
346       8 GB
347       4 GB
348       8 GB
349      16 GB
350      64 GB
351      16 GB
352      32 GB
353       4 GB
354      32 GB
355       4 GB
356      16 GB
357      16 GB
358       8 GB
359       4 GB
360      16 GB
361      16 GB
362      16 GB
363      16 GB
364      16 GB
365       8 GB
366      16 GB
367      16 GB
368      16 GB
369      16 GB
370       8 GB
371      16 GB
372       4 GB
373       4 GB
374      16 GB
375       8 GB
376      24 GB
377      16 GB
378       8 GB
379      16 GB
380      16 GB
381      32 GB
382      16 GB
383      16 GB
384      32 GB
385      16 GB
386      16 GB
387      16 GB
388      16 GB
389      32 GB
390      16 GB
391      32 GB
392      16 GB
393      16 GB
394      16 GB
395      16 GB
396      16 GB
397      32 GB
398       8 GB
399      32 GB
400       8 GB
401       8 GB
402       4 GB
403       8 GB
404      16 GB
405       8 GB
406       8 GB
407       8 GB
408       8 GB
409       8 GB
410       4 GB
411       8 GB
412       4 GB
413       8 GB
414       8 GB
415       4 GB
416       8 GB
417       8 GB
418       4 GB
419       8 GB
420       8 GB
421      16 GB
422      16 GB
423       8 GB
424      16 GB
425       8 GB
426       8 GB
427       8 GB
428       4 GB
429      16 GB
430       4 GB
431      16 GB
432      16 GB
433       8 GB
434       8 GB
435       8 GB
436       8 GB
437       4 GB
438       4 GB
439       4 GB
440       8 GB
441       4 GB
442       8 GB
443       4 GB
444       8 GB
445       8 GB
446       4 GB
447      16 GB
448       8 GB
449      16 GB
450       4 GB
451       4 GB
452       8 GB
453       2 GB
454       4 GB
455       4 GB
456       4 GB
457       4 GB
458       4 GB
459       8 GB
460       8 GB
461       8 GB
462       4 GB
463      16 GB
464       8 GB
465       4 GB
466       8 GB
467       8 GB
468       8 GB
469      16 GB
470       8 GB
471       8 GB
472      16 GB
473      16 GB
474       4 GB
475       8 GB
476       8 GB
477       8 GB
478       4 GB
479       8 GB
480       4 GB
481       8 GB
482       4 GB
483       8 GB
484       8 GB
485       8 GB
486       8 GB
487       8 GB
488       8 GB
489       8 GB
490       8 GB
491       8 GB
492      16 GB
493       8 GB
494       8 GB
495      16 GB
496       8 GB
497       4 GB
498      16 GB
499       8 GB
500       4 GB
501      16 GB
502       8 GB
503       8 GB
504       8 GB
505       8 GB
506       8 GB
507       8 GB
508       4 GB
509       4 GB
510       8 GB
511       8 GB
512       8 GB
513       4 GB
514       8 GB
515      16 GB
516       2 GB
517       8 GB
518       8 GB
519       8 GB
520       4 GB
521       8 GB
522       8 GB
523       4 GB
524       4 GB
525       4 GB
526       8 GB
527       4 GB
528       8 GB
529       8 GB
530       4 GB
531       4 GB
532       8 GB
533       2 GB
534       8 GB
535       4 GB
536       8 GB
537       3 GB
538      16 GB
539       4 GB
540       8 GB
541      16 GB
542       4 GB
543       4 GB
544       8 GB
545       4 GB
546      16 GB
547       8 GB
548       8 GB
549       4 GB
550      16 GB
551       4 GB
552       8 GB
553      16 GB
554       4 GB
555      16 GB
556       4 GB
557      16 GB
558       8 GB
559       8 GB
560       8 GB
561       8 GB
562       4 GB
563      16 GB
564       4 GB
565      16 GB
566       8 GB
567       8 GB
568       8 GB
569       8 GB
570       8 GB
571      16 GB
572       8 GB
573      16 GB
574       8 GB
575       8 GB
576       8 GB
577       8 GB
578       8 GB
579       8 GB
580       8 GB
581       8 GB
582      16 GB
583       4 GB
584       8 GB
585       4 GB
586       8 GB
587       2 GB
588      16 GB
589      16 GB
590      16 GB
591      16 GB
592       8 GB
593      16 GB
594       8 GB
595       4 GB
596       4 GB
597       8 GB
598      16 GB
599      16 GB
600      16 GB
601      32 GB
602       8 GB
603      16 GB
604      32 GB
605      32 GB
606       8 GB
607      12 GB
608      16 GB
609      16 GB
610      16 GB
611      16 GB
612      32 GB
613      16 GB
614      32 GB
615      16 GB
616      32 GB
617      16 GB
618      16 GB
619      16 GB
620       8 GB
621       8 GB
622      16 GB
623      32 GB
624       8 GB
625      32 GB
626      16 GB
627      16 GB
628       8 GB
629      16 GB
630      16 GB
631      16 GB
632      32 GB
633      16 GB
634      12 GB
635      16 GB
636      64 GB
637      16 GB
638      16 GB
639      16 GB
640      16 GB
641      16 GB
642      16 GB
643      16 GB
644      16 GB
645      16 GB
646       8 GB
647      32 GB
648      32 GB
649      16 GB
650      16 GB
651       8 GB
652      16 GB
653      16 GB
654      16 GB
655      16 GB
656      16 GB
657      16 GB
658      16 GB
659      16 GB
660      16 GB
661      16 GB
662       8 GB
663      16 GB
664      16 GB
665      16 GB
666      16 GB
667      16 GB
668      16 GB
669      16 GB
670      64 GB
671       8 GB
672      32 GB
673      32 GB
674      32 GB
675       8 GB
676      16 GB
677      24 GB
678      24 GB
679      16 GB
680       8 GB
681      16 GB
682      16 GB
683       8 GB
684      16 GB
685      16 GB
686      16 GB
687      32 GB
688      32 GB
689      16 GB
690      32 GB
691      64 GB
692      32 GB
693      64 GB
694      32 GB
695      64 GB
696      32 GB
697      16 GB
698       8 GB
699      24 GB
700      16 GB
701      16 GB
702       8 GB
703      16 GB
704      32 GB
705      16 GB
706      32 GB
707      24 GB
708      16 GB
709      16 GB
710      16 GB
711      16 GB
712      16 GB
713      32 GB
714      24 GB
715      32 GB
716      16 GB
717      16 GB
718      32 GB
719       8 GB
720      16 GB
721      32 GB
722      16 GB
723      32 GB
724      16 GB
725      16 GB
726      16 GB
727      16 GB
728       8 GB
729      16 GB
730      16 GB
731      16 GB
732      16 GB
733      32 GB
734      16 GB
735      16 GB
736      16 GB
737      32 GB
738      16 GB
739      32 GB
740      32 GB
741      32 GB
742       8 GB
743       8 GB
744      32 GB
745       8 GB
746      16 GB
747      16 GB
748      16 GB
749      64 GB
750       8 GB
751       4 GB
752      16 GB
753      16 GB
754      16 GB
755       8 GB
756      16 GB
757       8 GB
758      32 GB
759      32 GB
760      32 GB
761      16 GB
762       8 GB
763      16 GB
764      16 GB
765       8 GB
766       8 GB
767       8 GB
768      16 GB
769      16 GB
770       8 GB
771      16 GB
772       8 GB
773      16 GB
774       8 GB
775      16 GB
776      16 GB
777      16 GB
778      16 GB
779       8 GB
780      16 GB
781      16 GB
782       8 GB
783      16 GB
784      16 GB
785      16 GB
786      16 GB
787      16 GB
788      16 GB
789      32 GB
790      32 GB
791      16 GB
792      16 GB
793       8 GB
794      16 GB
795       4 GB
796       8 GB
797       8 GB
798       4 GB
799       8 GB
800       4 GB
801       8 GB
802       8 GB
803       8 GB
804       8 GB
805       8 GB
806       8 GB
807       8 GB
808       8 GB
809       8 GB
810      16 GB
811       8 GB
812       4 GB
813       8 GB
814       4 GB
815      16 GB
816      16 GB
817       4 GB
818       8 GB
819       8 GB
820       8 GB
821       8 GB
822       4 GB
823       4 GB
824       8 GB
825       8 GB
826       8 GB
827       8 GB
828       8 GB
829       4 GB
830       4 GB
831       4 GB
832       4 GB
833       8 GB
834       8 GB
835       8 GB
836       8 GB
837       8 GB
838       2 GB
839       4 GB
840       8 GB
841       4 GB
842       8 GB
843       4 GB
844       8 GB
845       4 GB
846       8 GB
847       4 GB
848       4 GB
849       4 GB
850       4 GB
851       8 GB
852       4 GB
853       8 GB
854       8 GB
855       8 GB
856       4 GB
857       8 GB
858       8 GB
859       2 GB
860       8 GB
861       8 GB
862      16 GB
863       8 GB
864      16 GB
865       8 GB
866      16 GB
867       8 GB
868       8 GB
869       8 GB
870      16 GB
871       4 GB
872       8 GB
873       8 GB
874       8 GB
875       4 GB
876       4 GB
877       8 GB
878       8 GB
879       8 GB
880      16 GB
881       8 GB
882       8 GB
883       8 GB
884       4 GB
885       8 GB
886       4 GB
887      16 GB
888       8 GB
889       8 GB
890       4 GB
891       4 GB
892       8 GB
893       8 GB
894      16 GB
895       8 GB
896       4 GB
897      16 GB
898       8 GB
899       8 GB
900       4 GB
901       8 GB
902       8 GB
903       8 GB
904       8 GB
905       8 GB
906       4 GB
907       8 GB
908       4 GB
909       8 GB
910       4 GB
911       8 GB
912       4 GB
913       8 GB
914       8 GB
915       8 GB
916       4 GB
917       4 GB
918       8 GB
919       4 GB
920       8 GB
921      16 GB
922       8 GB
923       8 GB
924      16 GB
925       8 GB
926       4 GB
927       4 GB
928       4 GB
929       8 GB
930       4 GB
931       8 GB
932      16 GB
933       8 GB
934       8 GB
935       4 GB
936       4 GB
937       8 GB
938      16 GB
939       8 GB
940       8 GB
941      16 GB
942       8 GB
943       2 GB
944       8 GB
945      16 GB
946       4 GB
947       8 GB
948       8 GB
949       8 GB
950       8 GB
951       8 GB
952       8 GB
953       8 GB
954       8 GB
955       8 GB
956       8 GB
957       8 GB
958      16 GB
959      16 GB
960       8 GB
961       8 GB
962       8 GB
963      16 GB
964      16 GB
965       8 GB
966       8 GB
967       4 GB
968       8 GB
969       8 GB
970       4 GB
971       4 GB
972       8 GB
973      16 GB
974      16 GB
975       8 GB
976       8 GB
977       8 GB
978       8 GB
979       8 GB
980       8 GB
981       8 GB
982       8 GB
983       8 GB
984       8 GB
985       8 GB
986       8 GB
987       8 GB
988       8 GB
989       8 GB
990      16 GB
991       8 GB
992       4 GB
993      16 GB
994       8 GB
995       8 GB
996       8 GB
997      16 GB
998       8 GB
999      16 GB
1000     64 GB
1001     32 GB
1002     16 GB
1003     16 GB
1004      8 GB
1005     16 GB
1006      8 GB
1007     16 GB
1008     16 GB
1009     16 GB
1010     16 GB
1011     16 GB
1012     16 GB
1013     16 GB
1014     16 GB
1015     16 GB
1016     16 GB
1017     16 GB
1018     32 GB
1019     16 GB
1020     16 GB
1021     32 GB
1022     16 GB
1023     16 GB
1024      8 GB
1025     16 GB
1026     32 GB
1027     16 GB
1028     16 GB
1029     16 GB
1030     16 GB
1031     16 GB
1032      8 GB
1033      8 GB
1034     16 GB
1035     16 GB
1036     16 GB
1037     16 GB
1038     16 GB
1039     16 GB
1040     16 GB
1041     16 GB
1042     16 GB
1043     16 GB
1044      8 GB
1045     16 GB
1046      8 GB
1047     32 GB
1048     16 GB
1049      8 GB
1050     16 GB
1051     16 GB
1052     32 GB
1053     16 GB
1054     32 GB
1055     32 GB
1056     16 GB
1057     16 GB
1058     16 GB
1059      8 GB
1060     16 GB
1061     16 GB
1062     16 GB
1063     16 GB
1064     12 GB
1065     16 GB
1066     16 GB
1067      8 GB
1068      8 GB
1069     16 GB
1070      8 GB
1071     32 GB
1072     16 GB
1073      8 GB
1074     16 GB
1075     16 GB
1076      8 GB
1077     16 GB
1078     16 GB
1079     16 GB
1080     16 GB
1081      8 GB
1082     16 GB
1083     32 GB
1084      8 GB
1085     16 GB
1086     16 GB
1087      8 GB
1088     16 GB
1089     16 GB
1090     16 GB
1091      8 GB
1092     32 GB
1093     16 GB
1094     16 GB
1095     16 GB
1096     32 GB
1097     16 GB
1098      8 GB
1099     32 GB
1100      8 GB
1101     16 GB
1102      8 GB
1103      8 GB
1104     16 GB
1105     16 GB
1106     32 GB
1107      8 GB
1108     16 GB
1109     32 GB
1110     32 GB
1111      8 GB
1112      8 GB
1113     16 GB
1114      8 GB
1115      8 GB
1116      8 GB
1117     16 GB
1118      8 GB
1119      8 GB
1120      8 GB
1121     16 GB
1122     16 GB
1123      8 GB
1124      8 GB
1125     16 GB
1126     16 GB
1127     16 GB
1128     16 GB
1129      8 GB
1130     32 GB
1131     32 GB
1132     32 GB
1133     32 GB
1134     16 GB
1135     32 GB
1136      8 GB
1137     16 GB
1138      8 GB
1139      8 GB
1140     16 GB
1141      8 GB
1142      8 GB
1143      8 GB
1144      8 GB
1145     16 GB
1146     16 GB
1147     16 GB
1148     16 GB
1149      8 GB
1150     16 GB
1151     16 GB
1152      8 GB
1153     16 GB
1154      8 GB
1155     16 GB
1156     16 GB
1157     16 GB
1158     16 GB
1159     16 GB
1160     16 GB
1161     16 GB
1162     16 GB
1163      8 GB
1164     16 GB
1165     16 GB
1166     16 GB
1167     16 GB
1168     16 GB
1169     24 GB
1170     16 GB
1171     32 GB
1172      8 GB
1173     16 GB
1174     32 GB
1175     64 GB
1176     64 GB
1177    128 GB
1178     32 GB
1179     16 GB
1180     16 GB
1181     16 GB
1182     16 GB
1183     16 GB
1184     16 GB
1185      8 GB
1186     16 GB
1187     16 GB
1188      8 GB
1189      8 GB
1190     16 GB
1191     16 GB
1192     16 GB
1193      8 GB
1194      8 GB
1195      8 GB
1196      4 GB
1197      4 GB
1198      4 GB
1199     16 GB
1200      8 GB
1201      8 GB
1202     16 GB
1203     16 GB
1204      8 GB
1205      8 GB
1206      8 GB
1207      8 GB
1208     16 GB
1209      8 GB
1210      8 GB
1211      8 GB
1212      8 GB
1213      4 GB
1214      8 GB
1215      8 GB
1216      8 GB
1217      4 GB
1218     16 GB
1219      8 GB
1220     16 GB
1221      8 GB
1222     16 GB
1223      8 GB
1224      4 GB
1225      8 GB
1226      8 GB
1227      4 GB
1228     16 GB
1229      8 GB
1230      8 GB
1231     16 GB
1232     16 GB
1233      8 GB
1234      8 GB
1235      8 GB
1236     16 GB
1237     16 GB
1238      8 GB
1239      4 GB
1240     16 GB
1241     16 GB
1242      8 GB
1243      8 GB
1244      8 GB
1245     16 GB
1246     16 GB
1247     16 GB
1248     16 GB
1249      8 GB
1250      8 GB
1251     16 GB
1252      8 GB
1253      8 GB
1254     16 GB
1255     16 GB
1256      8 GB
1257      8 GB
1258      8 GB
1259      8 GB
1260      8 GB
1261      8 GB
1262      8 GB
1263      8 GB
1264      4 GB
1265      8 GB
1266      8 GB
1267      8 GB
1268      4 GB
1269      8 GB
1270      8 GB
1271      4 GB
1272      8 GB
1273      8 GB
1274      8 GB
1275      4 GB
1276      4 GB
1277      8 GB
1278      8 GB
1279      8 GB
1280      8 GB
1281     16 GB
1282      8 GB
1283      4 GB
1284      8 GB
1285      8 GB
1286      8 GB
1287      8 GB
1288      8 GB
1289      8 GB
1290      8 GB
1291      8 GB
1292      4 GB
1293      4 GB
1294      8 GB
1295      4 GB
1296      8 GB
1297      8 GB
1298      8 GB
1299      8 GB
1300      8 GB
1301      8 GB
1302      8 GB
1303     16 GB
1304      8 GB
1305     16 GB
1306     16 GB
1307      8 GB
1308     16 GB
1309     16 GB
1310      8 GB
1311      8 GB
1312      8 GB
1313      8 GB
1314     16 GB
1315      4 GB
1316      4 GB
1317      8 GB
1318      8 GB
1319      8 GB
1320      4 GB
1321     16 GB
1322     16 GB
1323      8 GB
1324      4 GB
1325      8 GB
1326      8 GB
1327      8 GB
1328     16 GB
1329      4 GB
1330      8 GB
1331      4 GB
1332      8 GB

In [16]:
df["RAM_Capacity_GB"] = (
    df["Capacity"]
    .str.extract(r"([\d.]+)", expand=False)
    .astype(float)
)

In [17]:
df["RAM_Capacity_GB"]

0        16.0
1        16.0
2         8.0
3         8.0
4         4.0
5         8.0
6         8.0
7         4.0
8        16.0
9         8.0
10        8.0
11        4.0
12        8.0
13        8.0
14        4.0
15        8.0
16        8.0
17        8.0
18        8.0
19       16.0
20        8.0
21        8.0
22        8.0
23       16.0
24       16.0
25        8.0
26        4.0
27        8.0
28        8.0
29        8.0
30        8.0
31        8.0
32        8.0
33        8.0
34        8.0
35        4.0
36        8.0
37        8.0
38        8.0
39        4.0
40        8.0
41        8.0
42       16.0
43        8.0
44        4.0
45        8.0
46       16.0
47        8.0
48        8.0
49       16.0
50       16.0
51        8.0
52        8.0
53        8.0
54        8.0
55       16.0
56        8.0
57        8.0
58        8.0
59       16.0
60        4.0
61       16.0
62        8.0
63        4.0
64        4.0
65        8.0
66       16.0
67        8.0
68        8.0
69        8.0
70       16.0
71        4.0
72        4.0
73        8.0
74       16.0
75        8.0
76        8.0
77        8.0
78        8.0
79        8.0
80        4.0
81        8.0
82        8.0
83        8.0
84        8.0
85        4.0
86       16.0
87        8.0
88        8.0
89        8.0
90       16.0
91        8.0
92       16.0
93        8.0
94        8.0
95        8.0
96        8.0
97        8.0
98        8.0
99        8.0
100      16.0
101       8.0
102       8.0
103      16.0
104      16.0
105       8.0
106      16.0
107       8.0
108       4.0
109       8.0
110       8.0
111       8.0
112       8.0
113       8.0
114       8.0
115       4.0
116       4.0
117       8.0
118       8.0
119       8.0
120       8.0
121       4.0
122      16.0
123       8.0
124       8.0
125       8.0
126       8.0
127      16.0
128      16.0
129       8.0
130       8.0
131       4.0
132       8.0
133       4.0
134       4.0
135      16.0
136       8.0
137       4.0
138       8.0
139       4.0
140       4.0
141       8.0
142       8.0
143       8.0
144       8.0
145       8.0
146       8.0
147      16.0
148       8.0
149      16.0
150       8.0
151       4.0
152      16.0
153       8.0
154       8.0
155      32.0
156      16.0
157       8.0
158       8.0
159       8.0
160       8.0
161       8.0
162       8.0
163       4.0
164       8.0
165       8.0
166       8.0
167       4.0
168       4.0
169       8.0
170       8.0
171       8.0
172       8.0
173       8.0
174      16.0
175       8.0
176       8.0
177       8.0
178       8.0
179       4.0
180       8.0
181       4.0
182       8.0
183       8.0
184       8.0
185      16.0
186       8.0
187      16.0
188       8.0
189       8.0
190       8.0
191      16.0
192       8.0
193       4.0
194       8.0
195       8.0
196       4.0
197       8.0
198       8.0
199       8.0
200       4.0
201      16.0
202       8.0
203      16.0
204       8.0
205       4.0
206       8.0
207       4.0
208       8.0
209       2.0
210       4.0
211       4.0
212       4.0
213       4.0
214       8.0
215       2.0
216       4.0
217      16.0
218       4.0
219       4.0
220       4.0
221       2.0
222      16.0
223      16.0
224       8.0
225       4.0
226       4.0
227       8.0
228       8.0
229       4.0
230       8.0
231       8.0
232       8.0
233      16.0
234       4.0
235       8.0
236       2.0
237       4.0
238       4.0
239       4.0
240       4.0
241       4.0
242      16.0
243      16.0
244      16.0
245       4.0
246       4.0
247      16.0
248       8.0
249       4.0
250       4.0
251       8.0
252       4.0
253      16.0
254       8.0
255       8.0
256      16.0
257       2.0
258       8.0
259       8.0
260       4.0
261       4.0
262       8.0
263       4.0
264       4.0
265      16.0
266       8.0
267       4.0
268       8.0
269      16.0
270      16.0
271      16.0
272       2.0
273       8.0
274       8.0
275      16.0
276       4.0
277       4.0
278       8.0
279       8.0
280      16.0
281       4.0
282       8.0
283       2.0
284      16.0
285      32.0
286      16.0
287      16.0
288      16.0
289      16.0
290      16.0
291      16.0
292      64.0
293       8.0
294       4.0
295       4.0
296      16.0
297       4.0
298       8.0
299      16.0
300      16.0
301       2.0
302      16.0
303      16.0
304       4.0
305       4.0
306      16.0
307      16.0
308      16.0
309       4.0
310      32.0
311       4.0
312       8.0
313       4.0
314       8.0
315      32.0
316      16.0
317      16.0
318      32.0
319      16.0
320       8.0
321       8.0
322       8.0
323       4.0
324       4.0
325       4.0
326      32.0
327       8.0
328      16.0
329       8.0
330       8.0
331      32.0
332      16.0
333      16.0
334      16.0
335       8.0
336      32.0
337       4.0
338      16.0
339      16.0
340      16.0
341       4.0
342       8.0
343      16.0
344      16.0
345       4.0
346       8.0
347       4.0
348       8.0
349      16.0
350      64.0
351      16.0
352      32.0
353       4.0
354      32.0
355       4.0
356      16.0
357      16.0
358       8.0
359       4.0
360      16.0
361      16.0
362      16.0
363      16.0
364      16.0
365       8.0
366      16.0
367      16.0
368      16.0
369      16.0
370       8.0
371      16.0
372       4.0
373       4.0
374      16.0
375       8.0
376      24.0
377      16.0
378       8.0
379      16.0
380      16.0
381      32.0
382      16.0
383      16.0
384      32.0
385      16.0
386      16.0
387      16.0
388      16.0
389      32.0
390      16.0
391      32.0
392      16.0
393      16.0
394      16.0
395      16.0
396      16.0
397      32.0
398       8.0
399      32.0
400       8.0
401       8.0
402       4.0
403       8.0
404      16.0
405       8.0
406       8.0
407       8.0
408       8.0
409       8.0
410       4.0
411       8.0
412       4.0
413       8.0
414       8.0
415       4.0
416       8.0
417       8.0
418       4.0
419       8.0
420       8.0
421      16.0
422      16.0
423       8.0
424      16.0
425       8.0
426       8.0
427       8.0
428       4.0
429      16.0
430       4.0
431      16.0
432      16.0
433       8.0
434       8.0
435       8.0
436       8.0
437       4.0
438       4.0
439       4.0
440       8.0
441       4.0
442       8.0
443       4.0
444       8.0
445       8.0
446       4.0
447      16.0
448       8.0
449      16.0
450       4.0
451       4.0
452       8.0
453       2.0
454       4.0
455       4.0
456       4.0
457       4.0
458       4.0
459       8.0
460       8.0
461       8.0
462       4.0
463      16.0
464       8.0
465       4.0
466       8.0
467       8.0
468       8.0
469      16.0
470       8.0
471       8.0
472      16.0
473      16.0
474       4.0
475       8.0
476       8.0
477       8.0
478       4.0
479       8.0
480       4.0
481       8.0
482       4.0
483       8.0
484       8.0
485       8.0
486       8.0
487       8.0
488       8.0
489       8.0
490       8.0
491       8.0
492      16.0
493       8.0
494       8.0
495      16.0
496       8.0
497       4.0
498      16.0
499       8.0
500       4.0
501      16.0
502       8.0
503       8.0
504       8.0
505       8.0
506       8.0
507       8.0
508       4.0
509       4.0
510       8.0
511       8.0
512       8.0
513       4.0
514       8.0
515      16.0
516       2.0
517       8.0
518       8.0
519       8.0
520       4.0
521       8.0
522       8.0
523       4.0
524       4.0
525       4.0
526       8.0
527       4.0
528       8.0
529       8.0
530       4.0
531       4.0
532       8.0
533       2.0
534       8.0
535       4.0
536       8.0
537       3.0
538      16.0
539       4.0
540       8.0
541      16.0
542       4.0
543       4.0
544       8.0
545       4.0
546      16.0
547       8.0
548       8.0
549       4.0
550      16.0
551       4.0
552       8.0
553      16.0
554       4.0
555      16.0
556       4.0
557      16.0
558       8.0
559       8.0
560       8.0
561       8.0
562       4.0
563      16.0
564       4.0
565      16.0
566       8.0
567       8.0
568       8.0
569       8.0
570       8.0
571      16.0
572       8.0
573      16.0
574       8.0
575       8.0
576       8.0
577       8.0
578       8.0
579       8.0
580       8.0
581       8.0
582      16.0
583       4.0
584       8.0
585       4.0
586       8.0
587       2.0
588      16.0
589      16.0
590      16.0
591      16.0
592       8.0
593      16.0
594       8.0
595       4.0
596       4.0
597       8.0
598      16.0
599      16.0
600      16.0
601      32.0
602       8.0
603      16.0
604      32.0
605      32.0
606       8.0
607      12.0
608      16.0
609      16.0
610      16.0
611      16.0
612      32.0
613      16.0
614      32.0
615      16.0
616      32.0
617      16.0
618      16.0
619      16.0
620       8.0
621       8.0
622      16.0
623      32.0
624       8.0
625      32.0
626      16.0
627      16.0
628       8.0
629      16.0
630      16.0
631      16.0
632      32.0
633      16.0
634      12.0
635      16.0
636      64.0
637      16.0
638      16.0
639      16.0
640      16.0
641      16.0
642      16.0
643      16.0
644      16.0
645      16.0
646       8.0
647      32.0
648      32.0
649      16.0
650      16.0
651       8.0
652      16.0
653      16.0
654      16.0
655      16.0
656      16.0
657      16.0
658      16.0
659      16.0
660      16.0
661      16.0
662       8.0
663      16.0
664      16.0
665      16.0
666      16.0
667      16.0
668      16.0
669      16.0
670      64.0
671       8.0
672      32.0
673      32.0
674      32.0
675       8.0
676      16.0
677      24.0
678      24.0
679      16.0
680       8.0
681      16.0
682      16.0
683       8.0
684      16.0
685      16.0
686      16.0
687      32.0
688      32.0
689      16.0
690      32.0
691      64.0
692      32.0
693      64.0
694      32.0
695      64.0
696      32.0
697      16.0
698       8.0
699      24.0
700      16.0
701      16.0
702       8.0
703      16.0
704      32.0
705      16.0
706      32.0
707      24.0
708      16.0
709      16.0
710      16.0
711      16.0
712      16.0
713      32.0
714      24.0
715      32.0
716      16.0
717      16.0
718      32.0
719       8.0
720      16.0
721      32.0
722      16.0
723      32.0
724      16.0
725      16.0
726      16.0
727      16.0
728       8.0
729      16.0
730      16.0
731      16.0
732      16.0
733      32.0
734      16.0
735      16.0
736      16.0
737      32.0
738      16.0
739      32.0
740      32.0
741      32.0
742       8.0
743       8.0
744      32.0
745       8.0
746      16.0
747      16.0
748      16.0
749      64.0
750       8.0
751       4.0
752      16.0
753      16.0
754      16.0
755       8.0
756      16.0
757       8.0
758      32.0
759      32.0
760      32.0
761      16.0
762       8.0
763      16.0
764      16.0
765       8.0
766       8.0
767       8.0
768      16.0
769      16.0
770       8.0
771      16.0
772       8.0
773      16.0
774       8.0
775      16.0
776      16.0
777      16.0
778      16.0
779       8.0
780      16.0
781      16.0
782       8.0
783      16.0
784      16.0
785      16.0
786      16.0
787      16.0
788      16.0
789      32.0
790      32.0
791      16.0
792      16.0
793       8.0
794      16.0
795       4.0
796       8.0
797       8.0
798       4.0
799       8.0
800       4.0
801       8.0
802       8.0
803       8.0
804       8.0
805       8.0
806       8.0
807       8.0
808       8.0
809       8.0
810      16.0
811       8.0
812       4.0
813       8.0
814       4.0
815      16.0
816      16.0
817       4.0
818       8.0
819       8.0
820       8.0
821       8.0
822       4.0
823       4.0
824       8.0
825       8.0
826       8.0
827       8.0
828       8.0
829       4.0
830       4.0
831       4.0
832       4.0
833       8.0
834       8.0
835       8.0
836       8.0
837       8.0
838       2.0
839       4.0
840       8.0
841       4.0
842       8.0
843       4.0
844       8.0
845       4.0
846       8.0
847       4.0
848       4.0
849       4.0
850       4.0
851       8.0
852       4.0
853       8.0
854       8.0
855       8.0
856       4.0
857       8.0
858       8.0
859       2.0
860       8.0
861       8.0
862      16.0
863       8.0
864      16.0
865       8.0
866      16.0
867       8.0
868       8.0
869       8.0
870      16.0
871       4.0
872       8.0
873       8.0
874       8.0
875       4.0
876       4.0
877       8.0
878       8.0
879       8.0
880      16.0
881       8.0
882       8.0
883       8.0
884       4.0
885       8.0
886       4.0
887      16.0
888       8.0
889       8.0
890       4.0
891       4.0
892       8.0
893       8.0
894      16.0
895       8.0
896       4.0
897      16.0
898       8.0
899       8.0
900       4.0
901       8.0
902       8.0
903       8.0
904       8.0
905       8.0
906       4.0
907       8.0
908       4.0
909       8.0
910       4.0
911       8.0
912       4.0
913       8.0
914       8.0
915       8.0
916       4.0
917       4.0
918       8.0
919       4.0
920       8.0
921      16.0
922       8.0
923       8.0
924      16.0
925       8.0
926       4.0
927       4.0
928       4.0
929       8.0
930       4.0
931       8.0
932      16.0
933       8.0
934       8.0
935       4.0
936       4.0
937       8.0
938      16.0
939       8.0
940       8.0
941      16.0
942       8.0
943       2.0
944       8.0
945      16.0
946       4.0
947       8.0
948       8.0
949       8.0
950       8.0
951       8.0
952       8.0
953       8.0
954       8.0
955       8.0
956       8.0
957       8.0
958      16.0
959      16.0
960       8.0
961       8.0
962       8.0
963      16.0
964      16.0
965       8.0
966       8.0
967       4.0
968       8.0
969       8.0
970       4.0
971       4.0
972       8.0
973      16.0
974      16.0
975       8.0
976       8.0
977       8.0
978       8.0
979       8.0
980       8.0
981       8.0
982       8.0
983       8.0
984       8.0
985       8.0
986       8.0
987       8.0
988       8.0
989       8.0
990      16.0
991       8.0
992       4.0
993      16.0
994       8.0
995       8.0
996       8.0
997      16.0
998       8.0
999      16.0
1000     64.0
1001     32.0
1002     16.0
1003     16.0
1004      8.0
1005     16.0
1006      8.0
1007     16.0
1008     16.0
1009     16.0
1010     16.0
1011     16.0
1012     16.0
1013     16.0
1014     16.0
1015     16.0
1016     16.0
1017     16.0
1018     32.0
1019     16.0
1020     16.0
1021     32.0
1022     16.0
1023     16.0
1024      8.0
1025     16.0
1026     32.0
1027     16.0
1028     16.0
1029     16.0
1030     16.0
1031     16.0
1032      8.0
1033      8.0
1034     16.0
1035     16.0
1036     16.0
1037     16.0
1038     16.0
1039     16.0
1040     16.0
1041     16.0
1042     16.0
1043     16.0
1044      8.0
1045     16.0
1046      8.0
1047     32.0
1048     16.0
1049      8.0
1050     16.0
1051     16.0
1052     32.0
1053     16.0
1054     32.0
1055     32.0
1056     16.0
1057     16.0
1058     16.0
1059      8.0
1060     16.0
1061     16.0
1062     16.0
1063     16.0
1064     12.0
1065     16.0
1066     16.0
1067      8.0
1068      8.0
1069     16.0
1070      8.0
1071     32.0
1072     16.0
1073      8.0
1074     16.0
1075     16.0
1076      8.0
1077     16.0
1078     16.0
1079     16.0
1080     16.0
1081      8.0
1082     16.0
1083     32.0
1084      8.0
1085     16.0
1086     16.0
1087      8.0
1088     16.0
1089     16.0
1090     16.0
1091      8.0
1092     32.0
1093     16.0
1094     16.0
1095     16.0
1096     32.0
1097     16.0
1098      8.0
1099     32.0
1100      8.0
1101     16.0
1102      8.0
1103      8.0
1104     16.0
1105     16.0
1106     32.0
1107      8.0
1108     16.0
1109     32.0
1110     32.0
1111      8.0
1112      8.0
1113     16.0
1114      8.0
1115      8.0
1116      8.0
1117     16.0
1118      8.0
1119      8.0
1120      8.0
1121     16.0
1122     16.0
1123      8.0
1124      8.0
1125     16.0
1126     16.0
1127     16.0
1128     16.0
1129      8.0
1130     32.0
1131     32.0
1132     32.0
1133     32.0
1134     16.0
1135     32.0
1136      8.0
1137     16.0
1138      8.0
1139      8.0
1140     16.0
1141      8.0
1142      8.0
1143      8.0
1144      8.0
1145     16.0
1146     16.0
1147     16.0
1148     16.0
1149      8.0
1150     16.0
1151     16.0
1152      8.0
1153     16.0
1154      8.0
1155     16.0
1156     16.0
1157     16.0
1158     16.0
1159     16.0
1160     16.0
1161     16.0
1162     16.0
1163      8.0
1164     16.0
1165     16.0
1166     16.0
1167     16.0
1168     16.0
1169     24.0
1170     16.0
1171     32.0
1172      8.0
1173     16.0
1174     32.0
1175     64.0
1176     64.0
1177    128.0
1178     32.0
1179     16.0
1180     16.0
1181     16.0
1182     16.0
1183     16.0
1184     16.0
1185      8.0
1186     16.0
1187     16.0
1188      8.0
1189      8.0
1190     16.0
1191     16.0
1192     16.0
1193      8.0
1194      8.0
1195      8.0
1196      4.0
1197      4.0
1198      4.0
1199     16.0
1200      8.0
1201      8.0
1202     16.0
1203     16.0
1204      8.0
1205      8.0
1206      8.0
1207      8.0
1208     16.0
1209      8.0
1210      8.0
1211      8.0
1212      8.0
1213      4.0
1214      8.0
1215      8.0
1216      8.0
1217      4.0
1218     16.0
1219      8.0
1220     16.0
1221      8.0
1222     16.0
1223      8.0
1224      4.0
1225      8.0
1226      8.0
1227      4.0
1228     16.0
1229      8.0
1230      8.0
1231     16.0
1232     16.0
1233      8.0
1234      8.0
1235      8.0
1236     16.0
1237     16.0
1238      8.0
1239      4.0
1240     16.0
1241     16.0
1242      8.0
1243      8.0
1244      8.0
1245     16.0
1246     16.0
1247     16.0
1248     16.0
1249      8.0
1250      8.0
1251     16.0
1252      8.0
1253      8.0
1254     16.0
1255     16.0
1256      8.0
1257      8.0
1258      8.0
1259      8.0
1260      8.0
1261      8.0
1262      8.0
1263      8.0
1264      4.0
1265      8.0
1266      8.0
1267      8.0
1268      4.0
1269      8.0
1270      8.0
1271      4.0
1272      8.0
1273      8.0
1274      8.0
1275      4.0
1276      4.0
1277      8.0
1278      8.0
1279      8.0
1280      8.0
1281     16.0
1282      8.0
1283      4.0
1284      8.0
1285      8.0
1286      8.0
1287      8.0
1288      8.0
1289      8.0
1290      8.0
1291      8.0
1292      4.0
1293      4.0
1294      8.0
1295      4.0
1296      8.0
1297      8.0
1298      8.0
1299      8.0
1300      8.0
1301      8.0
1302      8.0
1303     16.0
1304      8.0
1305     16.0
1306     16.0
1307      8.0
1308     16.0
1309     16.0
1310      8.0
1311      8.0
1312      8.0
1313      8.0
1314     16.0
1315      4.0
1316      4.0
1317      8.0
1318      8.0
1319      8.0
1320      4.0
1321     16.0
1322     16.0
1323      8.0
1324      4.0
1325      8.0
1326      8.0
1327      8.0
1328     16.0
1329      4.0
1330      8.0
1331      4.0
1332      8.0
1333      8.0
1334      8.0
1335      8.0
1336      8.0
1337      8.0
1338      4.0
1339     16.0
1340      8.0
1341      8.0
1342      8.0
1343     16.0
1344      8.0
1345      8.0
1346      8.0
1347      8.0
1348      4.0
1349     16.0
1350     16.0
1351      8.0
1352      8.0
1353      8.0
1354     16.0
1355      8.0
1356      8.0
1357      8.0
1358      8.0
1359      8.0
1360      8.0
1361      4.0
1362      8.0
1363      4.0
1364      8.0
1365     16.0
1366      4.0
1367      8.0
1368      8.0
1369      8.0
1370      8.0
1371      8.0
1372      8.0
1373      8.0
1374     16.0
1375      8.0
1376     16.0
1377     32.0
1378     16.0
1379     16.0
1380      8.0
1381      8.0
1382      8.0
1383      4.0
1384      8.0
1385      8.0
1386      8.0
1387     16.0
1388      8.0
1389      8.0
1390     16.0
1391      4.0
1392      2.0
1393      4.0
1394      4.0
1395     16.0
1396      4.0
1397      4.0
1398     16.0
1399     16.0
1400      8.0
1401     16.0
1402      4.0
1403      4.0
1404     16.0
1405      8.0
1406      8.0
1407     16.0
1408      4.0
1409      4.0
1410      8.0
1411     16.0
1412     32.0
1413     16.0
1414     16.0
1415     16.0
1416     16.0
1417     16.0
1418     16.0
1419      4.0
1420     32.0
1421     16.0
1422     12.0
1423      4.0
1424      8.0
1425     16.0
1426      4.0
1427      4.0

In [18]:
final_features = [
    "Brand",
    "Series",
    "Thickness",
    "Weight",
    "Operating System",
    "Display Size",
    "Display Touchscreen",
    "Processor",
    "Graphic Processor",
    "RAM_Capacity_GB",
    "RAM Type",
    "SSD Capacity",
    "HDD Capacity",
    "Battery Capacity",
    "Fingerprint scanner"
]

target = "Price (Rs)"

In [19]:
df_ = df[final_features + [target]].copy()

In [20]:
print("Final df shape:", df_.shape)

Final df shape: (8176, 16)

In [21]:
print("\nFinal columns:")

for i, col in enumerate(df_.columns, start=1):
    print(f"{i}. {col}")

Final columns:
1. Brand
2. Series
3. Thickness
4. Weight
5. Operating System
6. Display Size
7. Display Touchscreen
8. Processor
9. Graphic Processor
10. RAM_Capacity_GB
11. RAM Type
12. SSD Capacity
13. HDD Capacity
14. Battery Capacity
15. Fingerprint scanner
16. Price (Rs)

In [22]:
missing_report = (
    df_.isna()
    .sum()
    .to_frame("Missing Count")
)

missing_report["Missing %"] = (
    missing_report["Missing Count"]
    / len(df_)
    * 100
)

print(missing_report)

                     Missing Count  Missing %
Brand                            0   0.000000
Series                        1090  13.331703
Thickness                      678   8.292564
Weight                         306   3.742661
Operating System                 0   0.000000
Display Size                     3   0.036693
Display Touchscreen             82   1.002935
Processor                        0   0.000000
Graphic Processor               92   1.125245
RAM_Capacity_GB                  0   0.000000
RAM Type                       170   2.079256
SSD Capacity                  1333  16.303816
HDD Capacity                  6323  77.336106
Battery Capacity              5732  70.107632
Fingerprint scanner           2674  32.705479
Price (Rs)                       0   0.000000

In [23]:
numeric_features = df_[final_features].select_dtypes(
    include="number"
).columns.tolist()

categorical_features = df_[final_features].select_dtypes(
    exclude="number"
).columns.tolist()

print("Numerical features:")
print(numeric_features)

print("\nNumerical count:", len(numeric_features))

print("\nCategorical features:")
print(categorical_features)

print("\nCategorical count:", len(categorical_features))

Numerical features:
['Thickness', 'Weight', 'Display Size', 'RAM_Capacity_GB', 'SSD Capacity', 'HDD Capacity', 'Battery Capacity']

Numerical count: 7

Categorical features:
['Brand', 'Series', 'Operating System', 'Display Touchscreen', 'Processor', 'Graphic Processor', 'RAM Type', 'Fingerprint scanner']

Categorical count: 8

In [39]:
df_.to_csv("../data/processed/laptop_selected.csv", index=False)

In [40]:
print("=" * 60)
print("FINAL VALIDATION")
print("=" * 60)

print("Rows:", df_.shape[0])
print("Columns:", df_.shape[1])

print("\nPredictor count:", len(final_features))
print("Target:", target)

print("\nTarget missing values:",
      df_[target].isna().sum())

print("Duplicate rows:",
      df_.duplicated().sum())

print("\nNumerical feature count:",
      len(numeric_features))

print("Categorical feature count:",
      len(categorical_features))

print("\nFinal columns:")
print(df_.columns.tolist())

print("=" * 60)

============================================================
FINAL VALIDATION
============================================================
Rows: 8078
Columns: 16

Predictor count: 15
Target: Price (Rs)

Target missing values: 0
Duplicate rows: 0

Numerical feature count: 7
Categorical feature count: 8

Final columns:
['Brand', 'Series', 'Thickness', 'Weight', 'Operating System', 'Display Size', 'Display Touchscreen', 'Processor', 'Graphic Processor', 'RAM_Capacity_GB', 'RAM Type', 'SSD Capacity', 'HDD Capacity', 'Battery Capacity', 'Fingerprint scanner', 'Price (Rs)']
============================================================

In [41]:
df_.duplicated().sum()

np.int64(0)

In [42]:
duplicate_rows = df_[df_.duplicated(keep=False)]

print("Rows involved in exact duplicates:",len(duplicate_rows))

duplicate_rows.head(20)

Rows involved in exact duplicates: 0

Empty DataFrame
Columns: [Brand, Series, Thickness, Weight, Operating System, Display Size, Display Touchscreen, Processor, Graphic Processor, RAM_Capacity_GB, RAM Type, SSD Capacity, HDD Capacity, Battery Capacity, Fingerprint scanner, Price (Rs)]
Index: []

In [47]:
duplicates = df_[df_.duplicated(keep=False)]

print("Rows involved in exact duplicates:", len(duplicates))
print("Duplicate extras:", df_.duplicated().sum())

duplicates.sort_values(
    by=_.columns.tolist()
).head(30)

Rows involved in exact duplicates: 0
Duplicate extras: 0

Empty DataFrame
Columns: [Brand, Series, Thickness, Weight, Operating System, Display Size, Display Touchscreen, Processor, Graphic Processor, RAM_Capacity_GB, RAM Type, SSD Capacity, HDD Capacity, Battery Capacity, Fingerprint scanner, Price (Rs)]
Index: []

In [45]:
df_ = df_.drop_duplicates()

In [46]:
print("Shape after removing duplicates:", df_.shape)
print("Remaining duplicates:", df_.duplicated().sum())

Shape after removing duplicates: (8078, 16)
Remaining duplicates: 0